paths:
  root: /Volumes/Data/PycharmProjects/calibration/qubic/scripts/Calibration/source_calibration/skydip

  runs:
    - dataset: data/input/2026-03-11/2026-03-11_16.48.15__SkyDip
      output: data/output/2026-03-11/2026-03-11_16.48.15__SkyDip
      atmospheric_config: configs/atmosphere/atmosphere_2026-03-11.yaml

#    - dataset: data/input/2026-03-11/2026-03-11_16.37.17__SkyDip
#      output: data/output/2026-03-11/2026-03-11_16.37.17__SkyDip
#      atmospheric_config: configs/atmosphere/atmosphere_2026-03-11.yaml

#    - dataset: data/input/2026-03-11/2026-03-11_10.41.39__SkyDip
#      output: data/output/2026-03-11/2026-03-11_10.41.39__SkyDip
#      atmospheric_config: configs/atmosphere/atmosphere_2026-03-11.yaml

    - dataset: data/input/2026-03-16/2026-03-16_12.57.47__SkyDip
      output: data/output/2026-03-16/2026-03-16_12.57.47__SkyDip
      atmospheric_config: configs/atmosphere/atmosphere_2026-03-16.yaml

#    - dataset: data/input/2026-05-02/2026-05-02_12.01.22__SkyDip
#      output: data/output/2026-05-02/2026-05-02_12.01.22__SkyDip
#      atmospheric_config: configs/atmosphere/atmosphere_2026-05-02.yaml
#
#    - dataset: data/input/2026-05-04/2026-05-04_12.11.52__SkyDip
#      output: data/output/2026-05-04/2026-05-04_12.11.52__SkyDip
#      atmospheric_config: configs/atmosphere/atmosphere_2026-05-04.yaml
#
#    - dataset: data/input/2026-05-05/2026-05-05_10.28.23__SkyDip
#      output: data/output/2026-05-05/2026-05-05_10.28.23__SkyDip
#      atmospheric_config: configs/atmosphere/atmosphere_2026-05-05.yaml
#
#    - dataset: data/input/2026-05-06/2026-05-06_01.02.42__SkyDip
#      output: data/output/2026-05-06/2026-05-06_01.02.42__SkyDip
#      atmospheric_config: configs/atmosphere/atmosphere_2026-05-06.yaml

    - dataset: data/input/2026-05-13/2026-05-13_10.31.27__SkyDip
      output: data/output/2026-05-13/2026-05-13_10.31.27__SkyDip
      atmospheric_config: configs/atmosphere/atmosphere_2026-05-13.yaml

    - dataset: data/input/2026-05-14/2026-05-14_10.31.08__SkyDip
      output: data/output/2026-05-14/2026-05-14_10.31.08__SkyDip
      atmospheric_config: configs/atmosphere/atmosphere_2026-05-14.yaml

#    - dataset: data/input/2026-05-20/2026-05-20_00.04.31__SkyDip
#      output: data/output/2026-05-20/2026-05-20_00.04.31__SkyDip
#      atmospheric_config: configs/atmosphere/atmosphere_2026-05-20.yaml
#
#    - dataset: data/input/2026-05-21/2026-05-21_00.22.37__SkyDip
#      output: data/output/2026-05-21/2026-05-21_00.22.37__SkyDip
#      atmospheric_config: configs/atmosphere/atmosphere_2026-05-21.yaml
#
#    - dataset: data/input/2026-05-22/2026-05-22_00.31.07__SkyDip
#      output: data/output/2026-05-22/2026-05-22_00.31.07__SkyDip
#      atmospheric_config: configs/atmosphere/atmosphere_2026-05-22.yaml



tod_processing:
  centered: true
  normalized: false

calibration:
  tes_indices: 95 # it could be a list [95, 96, 97, 98] or all
  run_am_if_missing: true

preprocessing:
  az_velocity_threshold: 0.5 deg/s
  el_velocity_threshold: 0.5 deg/s
  min_block_duration: 5.0 s #20.0 s
  el_smooth_window: 101
  el_polyorder: 3

  up_left_extension: 3.0 s
  down_right_extension: 1.0 s

plots:
  linewidth: 0.9
  alpha: 0.9
  fit_linewidth: 2.0
  fit_alpha: 0.95
  show: false

noise:
  nperseg: 1024
  window: "hann"
  noverlap: None
  scaling: "density"
  detrend: "constant"
  selected_frequency: 100 u.Hz
  enabled: true