paths:
  root_path: /Volumes/Data/PycharmProjects/calibration/qubic/scripts/Calibration/source_calibration/skydip/data
  dataset_name: 2026-05-22_09.58.32__SkyDip
  output_root_dir: output
  atmosphere_config: /Volumes/Data/PycharmProjects/calibration/qubic/scripts/Calibration/source_calibration/skydip/configs/atmosphere_2026-05-22.yaml

calibration:
  tes_index: 95
  conversion_factor_mode: dataset_mean
  run_am_if_missing: true

atmosphere:
  parameter_strategy: band_average
  min_elevation_deg: 1.0

preprocessing:
  az_velocity_threshold: 0.02
  min_block_duration: 20.0
  el_smooth_window: 101
  el_polyorder: 3
  el_velocity_threshold: 0.05
  min_run_duration: 20.0
  up_left_extension: 3.0
  down_right_extension: 1.0

plots:
  linewidth: 0.9
  alpha: 0.9
  fit_linewidth: 2.0
  fit_alpha: 0.95
  show: true

noise:
  nperseg: 1024
  enabled: true