---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.13.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

# QUBIC +

We try to construct another hypotetical instrument, QUBIC+ which is a combination of QUBIC and Simons obervatory experiments. 

The maps of S4 have these parameters :

$$\nu_i \hspace{1cm} \Delta \nu_i \hspace{1cm} \sigma_i$$

with $\nu$ is the frequency, $\Delta \nu$ is the bandwidth and $\sigma$ is the RMS of noise maps. The index $i$ is the sub-band of the observations. We consider now QUBIC+ with those parameters :

$$\nu_i \times n \hspace{1cm} \frac{\Delta \nu_i}{n} \hspace{1cm} \sigma_i \times \frac{\sqrt{n} \times (1 + \epsilon)}{f}$$

with $n$ the number of reconstruted sub-bands. $\epsilon$ is the relative optimality because of bolometric interferometry, $f$ is the fraction of CMB-S4 sensitivity and goes from $ \sqrt{n} \times (1 + \epsilon)$ to $1$.

```{python}
import qubicplus
import pysm3
import pysm3.units as u
from pysm3 import utils
import numpy as np
from qubic import camb_interface as qc
import healpy as hp
import matplotlib.pyplot as plt
import os
import random as rd
import string
import qubic
from importlib import reload
import pickle

import fgbuster
from fgbuster import AnalyticComponent
from scipy import constants
from fgbuster import CMB, Dust, Synchrotron, MixingMatrix

plt.rc('figure',figsize=(16,4))
plt.rc('font',size=12)

center = qubic.equ2gal(0, -57)
# If there is not this command, the kernel shut down every time..
os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'
```

```{python}
nside=256

def get_coverage(fsky, nside, center_radec=[0., -57.]):
    center = qubic.equ2gal(center_radec[0], center_radec[1])
    uvcenter = np.array(hp.ang2vec(center[0], center[1], lonlat=True))
    uvpix = np.array(hp.pix2vec(nside, np.arange(12*nside**2)))
    ang = np.arccos(np.dot(uvcenter, uvpix))
    indices = np.argsort(ang)
    okpix = ang < -1
    okpix[indices[0:int(fsky * 12*nside**2)]] = True
    mask = np.zeros(12*nside**2)
    mask[okpix] = 1
    return mask

covmap = get_coverage(0.03, nside)
skyconfig = {'cmb':42, 'dust':'d0'}

thr = 0.1
mymask = (covmap > (np.max(covmap)*thr)).astype(int)
pixok = mymask > 0

plt.figure()
hp.mollview(covmap, title = 'Coverage map', cmap='jet')
plt.show()
```

```{python}
# Loading of dictionary from BI-CMBS4.ipynb 

### CMB-S4 config

freqs = np.array([20., 30., 40., 85., 95., 145., 155., 220., 270.])
bandwidth = np.array([5., 9., 12., 20.4, 22.8, 31.9, 34.1, 48.4, 59.4])
dnu_nu = bandwidth/freqs
beam_fwhm = np.array([11., 72.8, 72.8, 25.5, 25.5, 22.7, 22.7, 13., 13.])
mukarcmin_TT = np.array([16.5, 9.36, 11.85, 2.02, 1.78, 3.89, 4.16, 10.15, 17.4])
mukarcmin_EE = np.array([10.87, 6.2, 7.85, 1.34, 1.18, 1.8, 1.93, 4.71, 8.08])
mukarcmin_BB = np.array([10.23, 5.85, 7.4, 1.27, 1.12, 1.76, 1.89, 4.6, 7.89])
ell_min = np.array([30, 30, 30, 30, 30, 30, 30, 30, 30])
nside = np.array([512, 512, 512, 512, 512, 512, 512, 512, 512])
edges_min = freqs * (1. - dnu_nu/2)
edges_max = freqs * (1. + dnu_nu/2)
edges = [[edges_min[i], edges_max[i]] for i in range(len(freqs))]
s4_config = {
    'nbands': len(freqs),
    'frequency': freqs,
    'depth_p': 0.5*(mukarcmin_EE + mukarcmin_BB),
    'depth_i': mukarcmin_TT,
    'depth_e': mukarcmin_EE,
    'depth_b': mukarcmin_BB,
    'fwhm': beam_fwhm,
    'bandwidth': bandwidth,
    'dnu_nu': dnu_nu,
    'ell_min': ell_min,
    'nside': nside,
    'fsky': 0.03,
    'ntubes': 12,
    'nyears': 7.,
    'edges': edges,
    'effective_fraction': np.zeros(len(freqs))+1.
            }

def fct_subopt(nus):
    subnus = [150., 220]
    subval = [1.4, 1.2]
    fct_subopt = np.poly1d(np.polyfit(subnus, subval, 1))
    return fct_subopt(nus)

subnus = [150., 220]
subval = [1.4, 1.2]

def get_coverage(fsky, nside, center_radec=[0., -57.]):
    center = qubic.equ2gal(center_radec[0], center_radec[1])
    uvcenter = np.array(hp.ang2vec(center[0], center[1], lonlat=True))
    uvpix = np.array(hp.pix2vec(nside, np.arange(12*nside**2)))
    ang = np.arccos(np.dot(uvcenter, uvpix))
    indices = np.argsort(ang)
    okpix = ang < -1
    okpix[indices[0:int(fsky * 12*nside**2)]] = True
    mask = np.zeros(12*nside**2)
    mask[okpix] = 1
    return mask

def qubicify(config, qp_nsub, qp_effective_fraction):
    nbands = np.sum(qp_nsubs)
    qp_config = config.copy()
    for k in qp_config.keys():
        qp_config[k]=[]
    qp_config['nbands'] = nbands
    qp_config['fsky'] = config['fsky']
    qp_config['ntubes'] = config['ntubes']
    qp_config['nyears'] = config['nyears']
    qp_config['initial_band'] = []

    for i in range(len(config['frequency'])):
        #print(config['edges'][i][0], config['edges'][i][-1])
        newedges = np.linspace(config['edges'][i][0], config['edges'][i][-1], qp_nsubs[i]+1)
        #print(newedges)
        newfreqs = (newedges[0:-1]+newedges[1:])/2
        newbandwidth = newedges[1:] - newedges[0:-1]
        newdnu_nu = newbandwidth / newfreqs
        newfwhm = config['fwhm'][i] * config['frequency'][i]/newfreqs
        scalefactor_noise = np.sqrt(qp_nsubs[i]) * fct_subopt(config['frequency'][i]) / qp_effective_fraction[i]
        newdepth_p = config['depth_p'][i] * np.ones(qp_nsub[i]) * scalefactor_noise
        newdepth_i = config['depth_i'][i] * np.ones(qp_nsub[i]) * scalefactor_noise
        newdepth_e = config['depth_e'][i] * np.ones(qp_nsub[i]) * scalefactor_noise
        newdepth_b = config['depth_b'][i] * np.ones(qp_nsub[i]) * scalefactor_noise
        newell_min = np.ones(qp_nsub[i]) * config['ell_min'][i]
        newnside = np.ones(qp_nsub[i]) * config['nside'][i]
        neweffective_fraction = np.ones(qp_nsub[i]) * qp_effective_fraction[i]
        initial_band = np.ones(qp_nsub[i]) * config['frequency'][i]

        for k in range(qp_nsubs[i]):
            if qp_effective_fraction[i] != 0:
                qp_config['frequency'].append(newfreqs[k])
                if i >= 3:
                    qp_config['depth_p'].append(newdepth_p[k])
                    qp_config['depth_i'].append(newdepth_i[k])
                    qp_config['depth_e'].append(newdepth_e[k])
                    qp_config['depth_b'].append(newdepth_b[k])
                else:
                    qp_config['depth_p'].append(s4_config['depth_p'][i])
                    qp_config['depth_i'].append(s4_config['depth_i'][i])
                    qp_config['depth_e'].append(s4_config['depth_e'][i])
                    qp_config['depth_b'].append(s4_config['depth_b'][i])
                qp_config['fwhm'].append(newfwhm[k])
                qp_config['bandwidth'].append(newbandwidth[k])
                qp_config['dnu_nu'].append(newdnu_nu[k])
                qp_config['ell_min'].append(newell_min[k])
                qp_config['nside'].append(newnside[k])

                qp_config['effective_fraction'].append(neweffective_fraction[k])
                qp_config['initial_band'].append(initial_band[k])
        for k in range(qp_nsubs[i]+1):
            if qp_effective_fraction[i] != 0:
                qp_config['edges'].append(newedges[k])

        #qp_config['depth_p'][:3] = s4_config['depth_p'][:3]
        #qp_config['depth_i'][:3] = s4_config['depth_i'][:3]

    fields = ['frequency', 'depth_p', 'depth_i', 'depth_e', 'depth_b', 'fwhm', 'bandwidth',
              'dnu_nu', 'ell_min', 'nside', 'edges', 'effective_fraction', 'initial_band']
    for j in range(len(fields)):
        qp_config[fields[j]] = np.array(qp_config[fields[j]])

    return qp_config


covmap = get_coverage(0.03, nside=256)
thr = 0.1
mymask = (covmap > (np.max(covmap)*thr)).astype(int)
pixok = mymask > 0


qp_nsubs = np.array([1, 1, 1, 5, 5, 5, 5, 5, 5])
qp_effective_fraction = np.array([1, 1, 1, 1, 1, 1, 1, 1, 1])
qp_config=qubicify(s4_config, qp_nsubs, qp_effective_fraction)


plt.figure(figsize=(16, 5))
plt.subplot(1,2,1)
plt.errorbar(s4_config['frequency'], s4_config['depth_p'], xerr=s4_config['bandwidth']/2, fmt='ro', label='CMB-S4')
plt.errorbar(qp_config['frequency'], qp_config['depth_p'], xerr=qp_config['bandwidth']/2, fmt='bo', label='BI')
plt.xlabel('Frequency [GHz]')
plt.ylabel(r'Depth_p [$\mu$K.arcmin]')
plt.title('CMB-S4 Configuration')
plt.legend()
plt.subplot(1,2,2)
plt.errorbar(s4_config['frequency'], s4_config['fwhm'], xerr=s4_config['bandwidth']/2, fmt='ro', label='CMB-S4')
plt.errorbar(qp_config['frequency'], qp_config['fwhm'], xerr=qp_config['bandwidth']/2, fmt='bo', label='BI')
plt.xlabel('Frequency [GHz]')
plt.ylabel('FWHM [arcmin]')
plt.title('CMB-S4 Configuration')
plt.legend()
plt.show()
```

<!-- #region -->
To compute our maps, we created a python files **qubicplus** which allows to create maps according to the noise of CMB-S4 and for BI-S4. We have many caracteristics mandatory to compute those maps. Those caracteristics are in 2 dictionary :

+ **s4_config**
+ **qp_config**

Thoses 2 configuration contains many caracteristics :

- **nbands** : Number of bands
- **Frequency** : Frequency observed
- **depth_p** : Depths of polarisations maps, useful to compute noise maps of QU
- **depth_i** : Depths of intensity maps, useful to compute noise maps of I
- **fwhm** : Angular resolution in arcmin (can be modifie in function to have the always the same)
- **nside** : Pixelisation of maps
- **fsky** : sky fraction in %
- **edges** : edges for integration into bands (not used for instance)


We create class which take the dictionary and define itself the caracteristic seen before. So to compute maps you just have to define wome arguments :

- **same_resol** : If same_resol is None -> Maps are at true fwhm define by dictionary
               If same_resol is a number -> Maps are at this fwhm (all the same)
- **verbose** : If True -> print some text
- **coverage** : If coverage is None -> you have a fullsky map
- **beta** : beta depend on type of dust you put in, if model of dust is d0 so beta is ignore, if dust model is d02b, you define in beta -> [beta0, beta1, nubreak, nu0]

This function return if you put noise = True, 3 maps which is :

- All components maps + noise
- All components maps
- noise

If you turn off the noise, it return only :

- All components maps 
<!-- #endregion -->

```{python}
reload(qubicplus)

qp=qubicplus.BImaps(skyconfig, s4_config)

mapS4_noisy, mapS4_noiseless, noiseS4 = qp.getskymaps(same_resol=0, 
                                                      iib=False, 
                                                      verbose=True, 
                                                      coverage=covmap, 
                                                      noise=True, 
                                                      signoise=1.,
                                                      beta=[1.54, 1.54, 145, 145])
```

```{python}
reload(qubicplus)

qp=qubicplus.BImaps(skyconfig, s4_config)

mapS4_noisy_conv, mapS4_noiseless_conv, noiseS4_conv = qp.getskymaps(same_resol=0.5, 
                                                      iib=False, 
                                                      verbose=True, 
                                                      coverage=covmap, 
                                                      noise=True, 
                                                      signoise=1.,
                                                      beta=[1.54, 1.54, 145, 145])
```

```{python}
f=3

plt.figure(figsize=(16, 13))
hp.gnomview(mapS4_noisy[f, 0], rot=center, reso=15, cmap='jet', sub=(3, 3, 1), title='Noisy maps', 
            unit=r'$\mu K_{CMB}$')
hp.gnomview(mapS4_noiseless[f, 0], rot=center, reso=15, cmap='jet', sub=(3, 3, 2), title='Noiseless maps', 
            unit=r'$\mu K_{CMB}$')
hp.gnomview(noiseS4[f, 0], rot=center, reso=15, cmap='jet', sub=(3, 3, 3), title='Noise maps', 
            unit=r'$\mu K_{CMB}$')

hp.gnomview(mapS4_noisy[f, 1], rot=center, reso=15, cmap='jet', sub=(3, 3, 4), title='', 
            unit=r'$\mu K_{CMB}$')
hp.gnomview(mapS4_noiseless[f, 1], rot=center, reso=15, cmap='jet', sub=(3, 3, 5), title='', 
            unit=r'$\mu K_{CMB}$')
hp.gnomview(noiseS4[f, 1], rot=center, reso=15, cmap='jet', sub=(3, 3, 6), title='', 
            unit=r'$\mu K_{CMB}$')

hp.gnomview(mapS4_noisy[f, 2], rot=center, reso=15, cmap='jet', sub=(3, 3, 7), title='', 
            unit=r'$\mu K_{CMB}$')
hp.gnomview(mapS4_noiseless[f, 2], rot=center, reso=15, cmap='jet', sub=(3, 3, 8), title='', 
            unit=r'$\mu K_{CMB}$')
hp.gnomview(noiseS4[f, 2], rot=center, reso=15, cmap='jet', sub=(3, 3, 9), title='', 
            unit=r'$\mu K_{CMB}$')

plt.suptitle(r'Maps from CMB-S4 - $\nu$ = {:.2f} GHz'.format(s4_config['frequency'][f]), fontsize=20, y=1.05)
plt.show()
```

```{python}
f=3

plt.figure(figsize=(16, 13))
hp.gnomview(mapS4_noisy_conv[f, 0], rot=center, reso=15, cmap='jet', sub=(3, 3, 1), title='Noisy maps', 
            unit=r'$\mu K_{CMB}$')
hp.gnomview(mapS4_noiseless_conv[f, 0], rot=center, reso=15, cmap='jet', sub=(3, 3, 2), title='Noiseless maps', 
            unit=r'$\mu K_{CMB}$')
hp.gnomview(noiseS4_conv[f, 0], rot=center, reso=15, cmap='jet', sub=(3, 3, 3), title='Noise maps', 
            unit=r'$\mu K_{CMB}$')

hp.gnomview(mapS4_noisy_conv[f, 1], rot=center, reso=15, cmap='jet', sub=(3, 3, 4), title='', 
            unit=r'$\mu K_{CMB}$')
hp.gnomview(mapS4_noiseless_conv[f, 1], rot=center, reso=15, cmap='jet', sub=(3, 3, 5), title='', 
            unit=r'$\mu K_{CMB}$')
hp.gnomview(noiseS4_conv[f, 1], rot=center, reso=15, cmap='jet', sub=(3, 3, 6), title='', 
            unit=r'$\mu K_{CMB}$')

hp.gnomview(mapS4_noisy_conv[f, 2], rot=center, reso=15, cmap='jet', sub=(3, 3, 7), title='', 
            unit=r'$\mu K_{CMB}$')
hp.gnomview(mapS4_noiseless_conv[f, 2], rot=center, reso=15, cmap='jet', sub=(3, 3, 8), title='', 
            unit=r'$\mu K_{CMB}$')
hp.gnomview(noiseS4_conv[f, 2], rot=center, reso=15, cmap='jet', sub=(3, 3, 9), title='', 
            unit=r'$\mu K_{CMB}$')

plt.suptitle(r'Maps from CMB-S4 convolved - $\nu$ = {:.2f} GHz'.format(s4_config['frequency'][f]), fontsize=20, y=1.05)
plt.show()
```

```{python}
from importlib import reload

reload(qubicplus)

mapqp_noisy, mapqp_noiseless, noiseqp = qubicplus.BImaps(skyconfig, qp_config).getskymaps(same_resol=0, 
                                                      iib=False, 
                                                      verbose=True, 
                                                      coverage=covmap, 
                                                      noise=True, 
                                                      signoise=1.,
                                                      beta=[1.54, 1.54, 145, 145])
```

```{python}
f=5

plt.figure(figsize=(16, 13))
hp.gnomview(mapqp_noisy[f, 0], rot=center, reso=15, cmap='jet', sub=(3, 3, 1), title='Noisy maps', 
            unit=r'$\mu K_{CMB}$')
hp.gnomview(mapqp_noiseless[f, 0], rot=center, reso=15, cmap='jet', sub=(3, 3, 2), title='Noiseless maps', 
            unit=r'$\mu K_{CMB}$')
hp.gnomview(noiseqp[f, 0], rot=center, reso=15, cmap='jet', sub=(3, 3, 3), title='Noise maps', 
            unit=r'$\mu K_{CMB}$')

hp.gnomview(mapqp_noisy[f, 1], rot=center, reso=15, cmap='jet', sub=(3, 3, 4), title='', 
            unit=r'$\mu K_{CMB}$')
hp.gnomview(mapqp_noiseless[f, 1], rot=center, reso=15, cmap='jet', sub=(3, 3, 5), title='', 
            unit=r'$\mu K_{CMB}$')
hp.gnomview(noiseqp[f, 1], rot=center, reso=15, cmap='jet', sub=(3, 3, 6), title='', 
            unit=r'$\mu K_{CMB}$')

hp.gnomview(mapqp_noisy[f, 2], rot=center, reso=15, cmap='jet', sub=(3, 3, 7), title='', 
            unit=r'$\mu K_{CMB}$')
hp.gnomview(mapqp_noiseless[f, 2], rot=center, reso=15, cmap='jet', sub=(3, 3, 8), title='', 
            unit=r'$\mu K_{CMB}$')
hp.gnomview(noiseqp[f, 2], rot=center, reso=15, cmap='jet', sub=(3, 3, 9), title='', 
            unit=r'$\mu K_{CMB}$')

plt.suptitle(r'Maps from BI-S4 - $\nu$ = {:.2f} GHz'.format(qp_config['frequency'][f]), fontsize=20, y=1.05)
plt.show()
```

```{python}
plt.figure(figsize=(12, 10))
hp.gnomview(noiseS4[3, 1], rot=center, reso=15, cmap='jet', sub=(1, 2, 1), title='Q - Noise map - S4 - 85 GHz')
hp.gnomview(noiseqp[5, 1], rot=center, reso=15, cmap='jet', sub=(1, 2, 2), title='Q - Noise map - BI - 85 GHz')
plt.show()
```

```{python}
s4_config['frequency']
```

```{python}

```

# SED : one beta case

```{python}
reload(qubicplus)

mapS4 = qubicplus.BImaps({'dust':'d0', 'synchrotron':'s0'}, s4_config).getskymaps(
                                      same_resol=0, 
                                      verbose=True, 
                                      coverage=covmap, 
                                      noise=False, 
                                      signoise=1.,
                                      beta=[1.54, 1.54, 145, 145])

mapqp = qubicplus.BImaps({'dust':'d0', 'synchrotron':'s0'}, qp_config).getskymaps(
                                      same_resol=0, 
                                      verbose=True, 
                                      coverage=covmap, 
                                      noise=False, 
                                      signoise=1.,
                                      beta=[1.54, 1.54, 145, 145])


reload(qubicplus)

qp=qubicplus.BImaps({'dust':'d0'}, s4_config)

mapS4_dust = qp.getskymaps(same_resol=0, 
                                      verbose=True, 
                                      coverage=covmap, 
                                      noise=False, 
                                      signoise=1.,
                                     beta=[1.54, 1.54, 145, 145])

reload(qubicplus)

qp=qubicplus.BImaps({'synchrotron':'s0'}, s4_config)

mapS4_sync = qp.getskymaps(same_resol=0, 
                                      verbose=True, 
                                      coverage=covmap, 
                                      noise=False, 
                                      signoise=1.,
                                     beta=[1.54, 1.54, 145, 145])
```

```{python}
nus=np.linspace(20, 300, 300)

h_over_k_val = constants.h * 1e9 / constants.k  # Assumes frequencies in GHz

nu0_val_dust = 145
dust_model = fgbuster.component_model.Dust(nu0=nu0_val_dust, beta_d=1.54, temp=20)
sed_dust=dust_model.eval(nus)

mapS4_dust_pola = np.sqrt(mapS4_dust[:, 1, :]**2 + mapS4_dust[:, 2, :]**2)
s_dust = np.std(mapS4_dust_pola[:, pixok], axis=1)[5]


plt.figure(figsize=(10, 10))

# Dust
plt.loglog(nus, sed_dust*s_dust, label=r'd0 : $\beta_d = ${:.2f} & $T_d = ${:.2f} K'.format(1.54, 20))
#plt.scatter(s4_config['frequency'], np.std(mapS4_dust[:, :, pixok].T, axis=0)[2])

# Synchrotron
nu0_val_sync = 145
sync_model = Synchrotron(nu0=nu0_val_sync, beta_pl=-3)
sed_sync=sync_model.eval(nus)

mapS4_sync_pola = np.sqrt(mapS4_sync[:, 1, :]**2 + mapS4_sync[:, 2, :]**2)
s_sync=np.std(mapS4_sync_pola[:, pixok], axis=1)[5]

plt.loglog(nus, sed_sync*s_sync, label=r's0 : $\beta_s = ${:.2f}'.format(-3))
#plt.scatter(s4_config['frequency'], np.std(mapS4_sync_pola[:, pixok].T, axis=0))

# Sum 
def model_1beta(x, pars, extra_args=None):
    sync_amp = pars[0]
    sync_pl = pars[1]
    cmb = pars[2]
    dust_amp = pars[3]
    beta_dust = pars[4]
    dust = dust_amp * dust_model.eval(x) 
    sync = sync_amp * sync_model.eval(x)
    return cmb + dust + sync

pars_true = np.array([s_sync, -3, 0, s_dust, 1.54])
vals = model_1beta(nus, pars_true)

sed_s4=model_1beta(s4_config['frequency'], pars_true)
sed_qp=model_1beta(qp_config['frequency'], pars_true)

plt.loglog(nus, vals, '--k', label='Total Foregrounds')
plt.scatter(qp_config['frequency'], np.mean(mapqp[:, 0, pixok], axis=1)/np.mean(mapqp[15, 0, pixok], axis=0)
            , color='blue', label='BI Maps')
plt.scatter(s4_config['frequency'], np.mean(mapS4[:, 0, pixok], axis=1)/np.mean(mapS4[5, 0, pixok], axis=0)
            , color='red', label='S4 Maps')
#plt.scatter(qp_config['frequency'], sed_qp, color='blue', label='BI Maps')
#plt.scatter(s4_config['frequency'], sed_s4, color='red', label='CMB-S4 Maps')

plt.legend(fontsize=14, frameon=False)
plt.xlabel('Frequency [GHz]', fontsize=15)
plt.ylabel(r'SED [$\mu K_{CMB}$]', fontsize=15)
plt.show()
```

```{python}

```

```{python}
reload(qubicplus)

mapS4 = qubicplus.BImaps({'cmb':42, 'dust':'d0', 'synchrotron':'s0'}, s4_config).getskymaps(
                                      same_resol=0, 
                                      verbose=True, 
                                      coverage=covmap, 
                                      noise=False, 
                                      signoise=1.,
                                      beta=[1.54, 1.54, 145, 145])

reload(qubicplus)

qp=qubicplus.BImaps({'cmb':42}, s4_config)

mapS4_cmb = qp.getskymaps(same_resol=0, 
                                      verbose=True, 
                                      coverage=covmap, 
                                      noise=False, 
                                      signoise=1.,
                                     beta=[1.54, 1.54, 145, 145])
```

```{python}
cmb = CMB()
sed_cmb=cmb.eval(nus)

mapS4_cmb_pola = np.sqrt(mapS4_cmb[:, 1, :]**2 + mapS4_cmb[:, 2, :]**2)
s_cmb = np.std(mapS4_cmb_pola[:, pixok], axis=1)[5]
```

```{python}
h_over_k_val = constants.h * 1e9 / constants.k  # Assumes frequencies in GHz

nu0_val_dust = 145
dust_model = Dust(nu0=nu0_val_dust, beta_d=1.54, temp=20)
sed_dust=dust_model.eval(nus)

mapS4_dust_pola = np.sqrt(mapS4_dust[:, 1, :]**2 + mapS4_dust[:, 2, :]**2)
s_dust = np.std(mapS4_dust_pola[:, pixok], axis=1)[5]


plt.figure(figsize=(10, 10))

# Dust
plt.loglog(nus, sed_dust*s_dust, label=r'd0 : $\beta_d = ${:.2f} & $T_d = ${:.2f} K'.format(1.54, 20))
#plt.scatter(s4_config['frequency'], np.std(mapS4_dust[:, :, pixok].T, axis=0)[2])

# Synchrotron
nu0_val_sync = 145
sync_model = Synchrotron(nu0=nu0_val_sync, beta_pl=-3)
sed_sync=sync_model.eval(nus)

mapS4_sync_pola = np.sqrt(mapS4_sync[:, 1, :]**2 + mapS4_sync[:, 2, :]**2)
s_sync=np.std(mapS4_sync_pola[:, pixok], axis=1)[5]

plt.loglog(nus, sed_sync*s_sync, label=r's0 : $\beta_s = ${:.2f}'.format(-3))
#plt.scatter(s4_config['frequency'], np.std(mapS4_sync_pola[:, pixok].T, axis=0))

#CMB
plt.loglog(nus, sed_cmb*s_cmb, label=r'CMB')


# Sum 
def model_1beta(x, pars, extra_args=None):
    sync_amp = pars[0]
    sync_pl = pars[1]
    cmb = pars[2]
    dust_amp = pars[3]
    beta_dust = pars[4]
    dust = dust_amp * dust_model.eval(x) 
    sync = sync_amp * sync_model.eval(x)
    return cmb + dust + sync

pars_true = np.array([s_sync, -3, s_cmb, s_dust, 1.54])
vals = model_1beta(nus, pars_true)

sed_s4=model_1beta(s4_config['frequency'], pars_true)
sed_qp=model_1beta(qp_config['frequency'], pars_true)

plt.loglog(nus, vals, '--k', label='All Components')
#plt.scatter(qp_config['frequency'], np.mean(mapqp[:, 0, pixok], axis=1)/np.mean(mapqp[15, 0, pixok]), color='blue', label='BI Maps')
plt.scatter(s4_config['frequency'], np.mean(mapS4[:, 0, pixok], axis=1), color='red', label='CMB-S4 Maps')

plt.legend(fontsize=14, frameon=False)
plt.xlabel('Frequency [GHz]', fontsize=15)
plt.ylabel(r'SED [$\mu K_{CMB}$]', fontsize=15)
plt.ylim(0.01, 200)
plt.show()
```

# 2 beta case

```{python}
reload(qubicplus)

mapS4 = qubicplus.BImaps({'dust':'d02b', 'synchrotron':'s0'}, s4_config).getskymaps(
                                      same_resol=0, 
                                      verbose=True, 
                                      coverage=covmap, 
                                      noise=False, 
                                      signoise=1.,
                                      beta=[1.44, 2.64, 150, 145])

mapqp = qubicplus.BImaps({'dust':'d02b', 'synchrotron':'s0'}, qp_config).getskymaps(
                                      same_resol=0, 
                                      verbose=True, 
                                      coverage=covmap, 
                                      noise=False, 
                                      signoise=1.,
                                      beta=[1.44, 2.64, 150, 145])


reload(qubicplus)

qp=qubicplus.BImaps({'dust':'d02b'}, s4_config)

mapS4_dust = qp.getskymaps(same_resol=0, 
                                      verbose=True, 
                                      coverage=covmap, 
                                      noise=False, 
                                      signoise=1.,
                                     beta=[1.44, 2.64, 150, 145])

reload(qubicplus)

qp=qubicplus.BImaps({'synchrotron':'s0'}, s4_config)

mapS4_sync = qp.getskymaps(same_resol=0, 
                                      verbose=True, 
                                      coverage=covmap, 
                                      noise=False, 
                                      signoise=1.,
                                     beta=[1.44, 2.64, 150, 145])

reload(qubicplus)

qp=qubicplus.BImaps({'dust':'d02b'}, qp_config)

mapqp_dust = qp.getskymaps(same_resol=0, 
                                      verbose=True, 
                                      coverage=covmap, 
                                      noise=False, 
                                      signoise=1.,
                                     beta=[1.44, 2.64, 150, 145])

reload(qubicplus)

qp=qubicplus.BImaps({'synchrotron':'s0'}, qp_config)

mapqp_sync = qp.getskymaps(same_resol=0, 
                                      verbose=True, 
                                      coverage=covmap, 
                                      noise=False, 
                                      signoise=1.,
                                     beta=[1.44, 2.64, 150, 145])
```

```{python}
h_over_k_val = constants.h * 1e9 / constants.k  # Assumes frequencies in GHz

nu0_val_dust = 145
double_dust_model = fgbuster.component_model.Dust_2b(nu0=nu0_val_dust, beta_d0=1.44, beta_d1=2.64, nubreak=150, temp=20)
sed_dust=double_dust_model.eval(nus)

mapS4_dust_pola = np.sqrt(mapS4_dust[:, 1, :]**2 + mapS4_dust[:, 2, :]**2)
s_dust = np.std(mapS4_dust_pola[:, pixok], axis=1)[5]


plt.figure(figsize=(10, 10))

# Dust
#plt.loglog(nus, sed_dust*s_dust, label=r'Dust : $\beta_0 = ${:.2f} $\beta_1 = ${:.2f}'.format(1.44, 2.64))
#plt.scatter(s4_config['frequency'], np.std(mapS4_dust[:, :, pixok].T, axis=0)[2])

# Synchrotron
nu0_val_sync = 145
sync_model = Synchrotron(nu0=nu0_val_sync, beta_pl=-3)
sed_sync=sync_model.eval(nus)

mapS4_sync_pola = np.sqrt(mapS4_sync[:, 1, :]**2 + mapS4_sync[:, 2, :]**2)
s_sync=np.std(mapS4_sync_pola[:, pixok], axis=1)[5]

#plt.loglog(nus, sed_sync*s_sync, label=r'Synchrotron : $\beta_s = ${:.2f}'.format(-3))
#plt.scatter(s4_config['frequency'], np.std(mapS4_sync_pola[:, pixok].T, axis=0))

# Sum 
def model_2beta(x, pars, extra_args=None):
    sync_amp = pars[0]
    sync_pl = pars[1]
    cmb = pars[2]
    dust_amp = pars[3]
    beta0_dust = pars[4]
    beta1_dust = pars[5]
    nubreak_dust = pars[6]
    dust = dust_amp * double_dust_model.eval(x) 
    sync = sync_amp * sync_model.eval(x)
    return cmb + dust + sync

pars_true = np.array([s_sync, -3, 0, s_dust, 1.44, 2.64, 150])
vals = model_2beta(nus, pars_true)

sed_s4=model_2beta(s4_config['frequency'], pars_true)
sed_qp=model_2beta(qp_config['frequency'], pars_true)

plt.loglog(nus, vals*np.mean(mapS4[5, 0, :], axis=0), '--k', label='Total Foregrounds')
plt.scatter(qp_config['frequency'], np.mean(mapqp[:, 0, :], axis=1), color='blue', label='BI Maps')
plt.scatter(s4_config['frequency'], np.mean(mapS4[:, 0, :], axis=1), color='red', label='S4 Maps')
#plt.scatter(qp_config['frequency'], sed_qp, color='blue', label='BI Maps')
#plt.scatter(s4_config['frequency'], sed_s4, color='red', label='CMB-S4 Maps')

plt.axvline(150, ls=':', color='green', label=r'$\nu_{break}$')
plt.legend(fontsize=14, frameon=False)
plt.xlabel('Frequency [GHz]', fontsize=15)
plt.ylabel(r'SED [$\mu K_{CMB}$]', fontsize=15)
plt.show()
```

We've exaggerated the value of both $\beta$ just to see the break of SED in dust side. Here it's clear that at 150 GHz there is a break. Our maps seems to be well reconstructed and so follow the law that we expected.

```{python}
np.where(covmap !=0)
```

```{python}

```

```{python}

```
