path_out: 'test_to_remove/'
datafilename: 'MC'

CMB:
    cmb: True
    seed: 1                                 # CMB realization
    r: 0
    Alens: 1

Foregrounds:

    Dust: False                              # Thermal Dust emission
    Synchrotron: False                      # Synchrotron emission

QUBIC:

    ### This section control the parameters related to QUBIC
    
    instrument: 'DB'                        # Instrumental design (DB or UWB)
    npointings: 30                        # Number of time samples
    nsub_in: 6                             # Number of sub-acquisitions
    nsub_out: 6
    nrec: 2                                # Number of reconstructed frequency maps
    convolution_in: True                   # Angular resolution in the input TOD
    convolution_out: False                  # Angular resolution in the reconstruction
    bandpass_correction: True               # Correction to keep the edges of the integration band constant
    NOISE:                          
        ndet: 0                             # Level of detector noise
        npho150: 0                          # Level of photon noise at 150 GHz
        npho220: 0                          # Level of photon noise at 220 GHz
        detector_nep: 4.7e-17                 # NEP of detector noise
    SYNTHBEAM:
        synthbeam_kmax: 1                  # Order of synthesized beam diffraction (synthbeam_kmax = 1 means 9 peaks)
    dtheta: 15                             # Angle for coverage

SKY:

    ### This section control the reconstructed sky

    nside: 512                              # Nside of components
    coverage_cut: 0.15                      # Define a cut where the coverage is too low
    RA_center: 0                   
    DEC_center: -57

PLANCK:

    ### This section define which external data are we using

    external_data: False                        
    weight_planck: 0                            # Weight of Planck data within the QUBIC patch
    level_noise_planck: 1                       # Noise level for Planck data
    bandwidth_planck: 0.2                       # Multiplicative factor to define the bandwidth of Planck's data
    nsub_planck: 100                            # Number of sub acquisitions for Planck's data

Pipeline:
    mapmaking: True                              # Run MapMaking Pipeline
    spectrum: False                              # Compute Power Spectra of the frequency maps

PCG:

    ### This section control PCG parameters

    n_iter_pcg: 2                                   # Number of PCG iterations
    tol_pcg: 1.0e-12                                # Tolerance for PCG
    preconditioner: True
    gif: True
    resolution_plot: 15
    fwhm_plot: 0

Spectrum:

    ### This section define the parameters to compute the power spectra

    dl: 10                                      
    lmin: 20
    lmax: 120
    aposize: 10