path_out: "test/"
datafilename: "test"

CMB:
    cmb: False
    seed: 1                      # CMB realization
    r: 0
    Alens: 1

Foregrounds:
    Dust: False            # Thermal Dust emission
    Synchrotron: False     # Synchrotron emission

QUBIC:
    ### This section control the parameters related to QUBIC

    instrument: "MB"          # Instrumental design (MB, DB or UWB)
    configuration: "TD"       # Instrumental configuration (TD or FI)
    npointings: 1000 #8640          # Number of time samples
    nsub_in: 8                # Number of sub-acquisitions
    nsub_out: 8
    nrec: 1                             # Number of reconstructed frequency maps # must be a diviser of nsub_out because there is no weight in the way the nrec H are built from nsub_out H
    convolution_in: False                  # Angular resolution in the input TOD
    convolution_out: False              # Angular resolution in the reconstruction
    bandpass_correction: True               # Correction to keep the edges of the integration band constant
    NOISE:                          
        ndet: 1                           # Level of detector noise            # randomness not fixed for det and photon noise, to be checked
        npho150: 0                         # Level of photon noise at 150 GHz
        npho220: 0                          # Level of photon noise at 220 GHz
        detector_nep: 2.05e-16                 # NEP of detector noise # do two different parameters?
        duration_150: 0.273972603                     # Effective duration at 150 GHz
        duration_220: 1                    # Effective duration at 220 GHz
        seed_noise: 11111
    SYNTHBEAM:
        synthbeam_kmax: 1        # Order of synthesized beam diffraction (synthbeam_kmax = 1 means 9 peaks)
        synthbeam_fraction: 1
    dtheta: 11.5               # Angle for coverage
    POINTINGS:
        random_pointing: False     
        sweeping_pointing: False
        repeat_pointing: False
        scanning_strategy: True
        duration: 12              # hours
        
SKY:
    ### This section control the reconstructed sky

    nside: 64                # Nside of components
    coverage_cut: 0.1         # Define a cut where the coverage is too low
    RA_center: 245
    DEC_center: -61.45

PLANCK:
    ### This section define which external data are we using

    external_data: False                    
    weight_planck: 0             # Weight of Planck data within the QUBIC patch
    level_noise_planck: 0        # Noise level for Planck data
    seed_noise: 22222
    bandwidth_planck: 0.2        # Multiplicative factor to define the bandwidth of Planck's data
    nsub_planck: 100              # Number of sub acquisitions for Planck's data

Pipeline:
    mapmaking: True              # Run MapMaking Pipeline
    spectrum: False              # Compute Power Spectra of the frequency maps

PCG:
    ### This section control PCG parameters

    n_iter_pcg: 100            # Number of PCG iterations #100
    tol_pcg: 1.0e-08          # Tolerance for PCG
    preconditioner: True
    initial_guess_intensity_to_zero: True
    gif: True
    resolution_plot: 15
    fwhm_plot: 0

Spectrum:
    ### This section define the parameters to compute the power spectra

    dl: 30
    lmin: 40
    lmax: 255
    aposize: 10