# mandatory parameters
[path]
source = "/media/DataQubic/**/*(ScanFast)*"

[optional]
exclude = ["IV", "2023"]
destination = "cr_results"
mask = "masks"
vertical_points = 3
exponential_points = 6
std_coeff = 2
analysis_type = "all"
tes = [-1]
remove_files = true
dpi = 300


