---
jupyter:
  jupytext:
    formats: ipynb,Rmd
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.9.1
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

```{python}
import random
import healpy as hp
import glob
from scipy.optimize import curve_fit
import pickle
from importlib import reload
import time
import scipy
import os
import numpy as np
import matplotlib.pyplot as plt
import sys
import pylab
from pylab import arange, show, cm
from astropy import units as uq
import gc

### Specific qubic modules
from qubicpack.utilities import Qubic_DataDir
from pysimulators import FitsArray
import pysm3 
import pysm3.units as u
import pysm3.utils as utils
import qubic
from qubic import QubicSkySim as qss
from qubic import fibtools as ft
from qubic import camb_interface as qc
from qubic import SpectroImLib as si
from qubic import NamasterLib as nam
from qubic import mcmc
from pysimulators.interfaces.healpy import HealpixConvolutionGaussianOperator

### FGBuster functions module
from fgbuster import get_instrument, get_sky, get_observation, ilc, basic_comp_sep, harmonic_ilc, weighted_comp_sep, multi_res_comp_sep  # Predefined instrumental and sky-creation configurations
from fgbuster.visualization import corner_norm, plot_component
from fgbuster.mixingmatrix import MixingMatrix
from fgbuster.observation_helpers import _rj2cmb, _jysr2rj, get_noise_realization

# Imports needed for component separation
from fgbuster import (separation_recipes, xForecast, CMB, Dust, Synchrotron, FreeFree, PowerLaw,  # sky-fitting model
                      basic_comp_sep)  # separation routine

import ComponentSeparation
import Plots

# Widgets
import ipywidgets as widgets

reload(qss)
reload(ft)

plt.rc('figure', figsize=(16, 10))
plt.rc('font', size=15)
plt.rcParams['image.cmap'] = 'jet'
```

```{python}
### Some initializations, to be replaced with specific path, or to modify in bash
os.environ['QUBIC_DATADIR'] = '/home/mathias/Bureau/qubic/qubic'
os.environ['QUBIC_DICT'] = '/home/mathias/Bureau/qubic/qubic/dicts'
global_dir = Qubic_DataDir(datafile='instrument.py', datadir=os.environ['QUBIC_DATADIR'])
```

```{python}
### Qubic dictionaries for 150GHz and 220Ghz
config_150, config_220 = 'FI-150', 'FI-220'
dictfilename150 = global_dir + '/doc/FastSimulator/FastSimDemo_{}.dict'.format(config_150)
dictfilename220 = global_dir + '/doc/FastSimulator/FastSimDemo_{}.dict'.format(config_220)
d150, d220 = qubic.qubicdict.qubicDict(), qubic.qubicdict.qubicDict()
d150.read_from_file(dictfilename150)
d220.read_from_file(dictfilename220)
qub_dic = {'150': d150, '220': d220}
center = qubic.equ2gal(d150['RA_center'], d150['DEC_center'])
```

```{python}
### Read some stuff
    # Read dictionary chosen
d150['focal_length'] = 0.3
d150['nside'] = 256
    #Define the number of reconstruction bands:
nbands = 3
d150['nf_recon'] = nbands
```

```{python}
def coverage_func(qub_dic, nbands, is_2_band, fq, npoints):
    
    """
    Procedure that returns coverage maps either at both 150 and 220 or only 150 or 220
    
    inputs:
        qub_dic: dict, of the form {'150': qub_dic_150, '220': ...}
        nbands: int, number of subbands
        is_2_band: boolean, if user wants coverage for only 1 frequency band or for 2
        fq: int, either 150 or 220
        npoints: int, number of pointing points
    
    returns:
        q: qubic object
        cov: np.array, coverage map
    """
    
    if is_2_band == True:
        qubic_dict_150, qubic_dict_220 = qub_dic['150'], qub_dic['220']
        qubic_dict_150['nside'], qubic_dict_220['nside'] = 256, 256
        qubic_dict_150['nf_recon'] = nbands
        qubic_dict_220['nf_recon'] = nbands
        qubic_dict_150['nf_sub'] = nbands
        qubic_dict_220['nf_sub'] = nbands
        qubic_dict_150['npointings'] = npoints
        qubic_dict_220['npointings'] = npoints
        p150 = qubic.get_pointing(qubic_dict_150)
        p220 = qubic.get_pointing(qubic_dict_220)
        s150 = qubic.QubicScene(qubic_dict_150)
        s220 = qubic.QubicScene(qubic_dict_220)
        q150 = qubic.QubicMultibandInstrument(qubic_dict_150)
        q220 = qubic.QubicMultibandInstrument(qubic_dict_220)
        _, nus_edge_150, _, _, _, _ = qubic.compute_freq(150, qubic_dict_150['nf_sub'])
        _, nus_edge_220, _, _, _, _ = qubic.compute_freq(220, qubic_dict_220['nf_sub'])
        a150 = qubic.QubicMultibandAcquisition(q150, p150, s150, qubic_dict_150, nus_edge_150)
        a220 = qubic.QubicMultibandAcquisition(q220, p220, s220, qubic_dict_220, nus_edge_220)
        cov1 = a150.get_coverage()
        cov2 = a220.get_coverage()
        a150 = 0
        a220 = 0
        cov1 = np.sum(cov1, axis=0)
        cov2 = np.sum(cov2, axis=0)
        cov1 /= np.max(cov1)
        cov2 /= np.max(cov2)
        return q150, q220, cov1, cov2
    else:
        gc.collect()
        qubic_dict = qub_dic[str(fq)]
        qubic_dict['nside'] = 256
        qubic_dict['nf_recon'] = nbands
        qubic_dict['nf_sub'] = nbands
        qubic_dict['npointings'] = npoints
        p = qubic.get_pointing(qubic_dict)
        s = qubic.QubicScene(qubic_dict)
        q = qubic.QubicMultibandInstrument(qubic_dict)
        _, nus_edge, _, _, _, _ = qubic.compute_freq(fq, qubic_dict['nf_sub'])
        a = qubic.QubicMultibandAcquisition(q, p, s, qubic_dict, nus_edge)
        cov = a.get_coverage()
        a = 0
        cov = np.sum(cov, axis=0)
        cov /= np.max(cov)
        return q, cov
```

```{python}
npix = 12 * d150['nside'] ** 2
Nf = int(d150['nf_sub'])
band = d150['filter_nu'] / 1e9
filter_relative_bandwidth = d150['filter_relative_bandwidth']
a, nus_edge, nus_in, d, e, Nbbands_in = qubic.compute_freq(band, Nf, filter_relative_bandwidth)
```

```{python}
qub_dic['150']['dtheta'] = 50
```

```{python}
### Example of how it works ...
q150, cov150 = coverage_func(qub_dic, nbands, False, 150, 7000)
```

```{python}
hp.mollview(cov150)
```

```{python}
okpix_inside = (cov150 > (0.5*np.max(cov150)))
okpix_qubic = np.loadtxt('mask_fgbuster')
okpix_qubic = okpix_qubic != 0
```

```{python}
maps = cov150.copy()
maps[~okpix_qubic] = 0
hp.mollview(maps)
```

```{python}
hp.gnomview(maps, rot = center, reso = qub_dic['150']['dtheta'])
```

```{python}

```

```{python}

```

```{python}

```

Here we define all frequencies and FWHM and we decide the noise level and if we integrate into band.

```{python}
if nbands == 3 :
    freqs = [136.984337, 148.954079, 161.969742]
    fwhmdegs = [0.42999269, 0.39543908, 0.36366215]
elif nbands == 4 :
    freqs = [135.50540829,    144.29216391,    153.6486907 ,    163.61193508]
    fwhmdegs = [0.43468571,    0.40821527,    0.38335676,    0.36001202]
elif nbands == 5 :
    freqs = [134.63280448,    141.57278853,    148.8705114 ,    156.54441361,    164.61388627]
    fwhmdegs = [0.43750306,    0.41605639,    0.39566106,    0.37626551,    0.35782075]
else :
    raise TypeError('Incorrect frequency number')

fwhm_final = np.max(fwhmdegs) + 1e-10    # All maps will have this resolution

verbose = False
integration_into_band = True
nunu_correlation = False
FWHMdeg = fwhmdegs
spatial_noise = False
nyears = 4e10
```

```{python}
okpix = (cov150 > (0.1*np.max(cov150)))
```

```{python}
seed = 42
sky_config = {'dust': 'd0', 'cmb': seed}
Qubic_sky_150 = qss.Qubic_sky(sky_config, d150)


CMBdust, CMBdust_noiseless, CMBdust_noise, P = Qubic_sky_150.get_partial_sky_maps_withnoise(coverage=cov150,
                                       Nyears=nyears, verbose=verbose, FWHMdeg=FWHMdeg, seed = 42,
                                       spatial_noise=spatial_noise,
                                       nunu_correlation=nunu_correlation,
                                       integrate_into_band=integration_into_band
                                            )
CMBdust = np.transpose(CMBdust, (0, 2, 1))
CMBdust_noiseless = np.transpose(CMBdust_noiseless, (0, 2, 1))
CMBdust_noise = np.transpose(CMBdust_noise, (0, 2, 1))
```

```{python}
sky_config = {'cmb': seed}
Qubic_sky_150_cmb = qss.Qubic_sky(sky_config, d150)


cmb, CMB_noiseless, CMB_noise, _ = Qubic_sky_150_cmb.get_partial_sky_maps_withnoise(coverage=cov150,
                                       Nyears=nyears, verbose=verbose, FWHMdeg=FWHMdeg, seed = 42,
                                       spatial_noise=spatial_noise,
                                       nunu_correlation=nunu_correlation,
                                       integrate_into_band=integration_into_band)

cmb = np.transpose(cmb, (0, 2, 1))
CMB_noiseless = np.transpose(CMB_noiseless, (0, 2, 1))
CMB_noise = np.transpose(CMB_noise, (0, 2, 1))
```

```{python}
sky_config = {'dust': 'd0'}
Qubic_sky_150_dust = qss.Qubic_sky(sky_config, d150)

dust, dust_noiseless, dust_noise, _ = Qubic_sky_150_dust.get_partial_sky_maps_withnoise(coverage=cov150,
                                       Nyears=nyears, verbose=verbose, FWHMdeg=FWHMdeg, seed = 42,
                                       spatial_noise=spatial_noise,
                                       nunu_correlation=nunu_correlation,
                                       integrate_into_band=integration_into_band)
dust = np.transpose(dust, (0, 2, 1))
dust_noiseless = np.transpose(dust_noiseless, (0, 2, 1))
dust_noise = np.transpose(dust_noise, (0, 2, 1))
```

We put all maps at the same resolution to compare them.

```{python}
dust_same_resol, tab_fwhm, delta_fwhm = ComponentSeparation.same_resol(dust_noiseless, fwhmdegs, 
                                                                fwhm_target = fwhm_final, verbose=True)
```

```{python}
cmb_same_resol, tab_fwhm, delta_fwhm = ComponentSeparation.same_resol(CMB_noiseless, fwhmdegs, 
                                                                fwhm_target = fwhm_final, verbose=True)
```

```{python}
stk = ['I','Q','U']
reso = qub_dic['150']['dtheta']
jstk = 0
maps = cmb_same_resol.copy()
maps[:, :, okpix_qubic] = np.nan
plt.rc('figure', figsize=(22, 10))
itest = 0
plt.figure(figsize = (16, 10))
for i in range(len(freqs)):
    hp.gnomview(CMB_noiseless[i,jstk,:]-CMB_noiseless[itest,jstk,:], rot=center, reso=reso,
                sub=(nbands,len(freqs),len(freqs)*i+1), min=-1, max=1,
                title='$\Delta$CMBin {}-{} for {}'.format(i,itest,stk[jstk]))
    hp.gnomview(cmb_same_resol[i,jstk,:]-cmb_same_resol[itest,jstk,:], rot=center, reso=reso,
                sub=(nbands,len(freqs),len(freqs)*i+2), min=-1, max=1,
                title='$\Delta$CMBout {}-{} for {}'.format(i,itest,stk[jstk]))
    hp.gnomview(maps[i,jstk,:]-maps[itest,jstk,:], rot=center, reso=reso,
                sub=(nbands,len(freqs),len(freqs)*i+3), min=-1, max=1,
                title='$\Delta$CMBout {}-{} for {}'.format(i,itest,stk[jstk]))
plt.tight_layout()
plt.show()
```

This plot show different coverage, in green the initial coverage and in red a correction to take into account the bad convolution at the edges.

```{python}
maps = np.zeros(12*256**2)
maps[okpix] = 1
maps[okpix_qubic] = 2

hp.gnomview(maps, rot = center, reso = reso)
```

```{python}
reload(ComponentSeparation)
```

We call here the **fg_buster** function from **ComponentSeparation.py** to separe components.

```{python}
okpix = cov150 != 0
```

```{python}
indf = 0 # Choose a frequency for Dust
Stkp = 'QU'
okpix_maps = okpix_qubic.copy()

R = ComponentSeparation.CompSep(d150).fg_buster(CMBdust, 
        [CMB(), Dust(freqs[indf], temp = 20.)], freq = freqs, fwhmdeg = fwhmdegs, 
                                                target = fwhm_final, okpix = okpix_maps, Stokesparameter = Stkp)
```

To have an idea of the reconstruction quality, we show the $\beta_d$ and dust temperature which must be respectively $\beta_d = 1.54$ and $T = 20 K$

```{python}
print(' \n beta_d = {:.5f} \n'.format(R.x[0]))
```

```{python}
reload(ComponentSeparation)
```

We convert the R dictionary to arrays. The form of the final array is (Ncomp, Nfreq, Stokes, Npix) where Ncomp = 0 for the CMB, Ncomp = 1 for the dust and Ncomp = 2 for the synchrotron effect.

```{python}
#cmb_est_fg, dust_est_fg = ComponentSeparation.CompSep(d150).basic_2_tab(R, okpix_inside)
array_est_fg = ComponentSeparation.CompSep(d150).basic_2_tab(R, okpix_maps)
cmb_same_resol[:, :, ~okpix_qubic] = 0
dust_same_resol[:, :, ~okpix_qubic] = 0

array_est_fg[0][:, :, ~okpix_qubic] = 0
array_est_fg[1][:, :, ~okpix_qubic] = 0
```

```{python}
array_est_fg.shape
```

```{python}
reload(Plots)
```

```{python}
Plots.Plots.diff_2_maps(cmb_same_resol, array_est_fg[0], okpix_qubic, indf, center, 15,
                                                                'CMB', 'CMB est', Stokesparameter = Stkp)
```

```{python}
Plots.Plots.diff_2_maps(dust_same_resol, array_est_fg[1], okpix_qubic, indf, center, 15, 
                                              'Dust', 'Dust estimated', Stokesparameter = Stkp)
```

```{python}
ranges = [[-240, 240], [-5, 5], [-5, 5]]
Plots.Plots.diff_2_hist(cmb_same_resol, array_est_fg[0], okpix_qubic, indf, 'CMB in', 'CMB out', 
                        ranges = ranges, bins = 100, Stokesparameter = Stkp)
```

```{python}
ranges = [[0, 20], [-1, 6], [-3, 2]]
Plots.Plots.diff_2_hist(dust_same_resol, array_est_fg[1], okpix_qubic, indf, 'Dust in', 'Dust out', 
                        ranges = ranges, bins = 100, Stokesparameter = Stkp)
```

Here we plot all the results firstly for the reconstruction maps from FG-Buster algorithm and secondly for maps created by Qubic simulations (from **QubicSkySim.py**)


# Power spectrum

```{python}
### Input Dls
input_Dl = Qubic_sky_150_cmb.input_cmb_spectra
if input_Dl is not None:
    input_ell = np.arange(np.shape(input_Dl)[0])
    print('input_ell shape = ', input_ell.shape)
```

```{python}
# Create a Namaster object
lmin = 20
lmax = 2 * d150['nside'] - 1
delta_ell = 16

### Making mask - it will be automaticall apodized when instanciating the object with default (tunable) parameters
mask = np.zeros(12 * d150['nside']**2)
mask[okpix_inside] = 1

Namaster = nam.Namaster(mask, lmin=lmin, lmax=lmax, delta_ell=delta_ell)
```

```{python}
ell_binned, b = Namaster.get_binning(d150['nside'])

Dls_binned = Namaster.bin_spectra(input_Dl[:, 0], d150['nside'])
print('lmax=', lmax)

print(ell_binned.shape, Dls_binned.shape)

plt.rc('figure', figsize=(8, 6))
plt.figure()
plt.plot(input_ell[:lmax], input_Dl[:lmax, 0])
plt.plot(ell_binned, Dls_binned[0, :],'o')
plt.xlabel('$\\ell$')
plt.ylabel('$D_\\ell$')
```

```{python}
def Dl_2_Cl(Dl, l) :
    Df = np.zeros(Dl.shape)
    for i in range(Dl.shape[1]) :
        for j in range(Dl.shape[0]) :
            Df[j, i] = 2 * np.pi * Dl[j, i] / (l[j] * (l[j] + 1))
    return Df
```

```{python}
input_Dl = Qubic_sky_150_cmb.input_cmb_spectra
```

```{python}
lmax = 2 * d150['nside'] - 1
seenpix = (cov150 > (0.1*np.max(cov150)))
mask = np.zeros(12 * d150['nside']**2)
mask[seenpix] = 1
```

```{python}
# Namaster object

Namaster = nam.Namaster(mask, lmin=lmin, lmax=lmax, delta_ell=delta_ell)
```

```{python}
ell_binned, b = Namaster.get_binning(d150['nside'])
mask_apo = Namaster.mask_apo
Dls_binned = Namaster.bin_spectra(input_Dl[:, 0], d150['nside'])
```

```{python}
hp.gnomview(mask_apo, rot = center, reso = 50)
hp.gnomview(CMBdust[0, 0, :] * mask_apo, rot = center, reso = 25)
```

```{python}
pixwin = True
beam = np.max(fwhmdegs)
```

```{python}
# Get spectra
leff_cmb_est, cells_cmb_est, w_cmb_est = Namaster.get_spectra(array_est_fg[0][indf], purify_e=False, purify_b=True, 
                                                    beam_correction = beam, pixwin_correction=pixwin)
```

```{python}
# Get spectra
leff_cmb, cells_cmb, w_cmb = Namaster.get_spectra(cmb_same_resol[indf], purify_e=False, purify_b=True, 
                                                  beam_correction = beam, pixwin_correction=pixwin)
```

```{python}
clnames = ['TT', 'EE', 'BB', 'TE']

fig, ax = plt.subplots(2, 2, constrained_layout = True)
plt.rc('figure', figsize=(16, 10))
k = 0
for i in range(2) :
    for j in range(2) :

        ax[i, j].plot(input_ell[:lmax], input_Dl[:lmax, k], '-k')
        ax[i, j].plot(leff_cmb[:lmax], cells_cmb[:lmax, k],'or', label = 'CMB', markersize = 6)
        ax[i, j].plot(leff_cmb_est[:lmax], cells_cmb_est[:lmax, k],'xb', label = 'CMB est', markersize = 10)
        ax[i, j].set_xlabel('$\\ell$')
        ax[i, j].set_ylabel('$D_\\ell$')
        ax[i, j].set_title(clnames[k])
        ax[i, j].legend()

        k += 1
```

Above, we have all spectras of CMB (red dots), CMB estimated by FG-Buster (blue crosses) and theoretical CMB (black line). Here we are in a no noise case, the reconstruction of the spectras by FG-Buster is very efficient(comparison between blue crosses and red dots).

At the large scale (typically $\ell < 200$), there are a good agreement between FG-Buster and the theoretical spectra, but at the small scale, there is a difference between them. That is due to the fact that all maps are not at the same resolution, so the convolution delete some maps details. We can see that on below maps :

```{python}
input_maps = Qubic_sky_150_cmb.input_cmb_maps
```

```{python}
istk = 1
input_maps[istk, ~okpix_inside] = 0
cmb_same_resol[0, istk, ~okpix_inside] = 0
nsig = 3
sig1 = np.std(input_maps[istk, okpix_inside])
sig2 = np.std(array_est_fg[0][0, istk, okpix_inside])

hp.gnomview(input_maps[istk, :], rot = center, reso = 15, sub = (1, 3, 1), title = 'Theoretical map (1)'
           , min = -nsig * sig1, max = nsig * sig1)
hp.gnomview(cmb_same_resol[0, istk, :], rot = center, reso = 15, sub = (1, 3, 2), title = 'Map seen by the instrument (2)'
           , min = -nsig * sig2, max = nsig * sig2)
hp.gnomview(array_est_fg[0][0, istk, :], rot = center, reso = 15, sub = (1, 3, 3), title = 'Reconstruction by FG-Buster (3)'
           , min = -nsig * sig2, max = nsig * sig2)
```

```{python}
hp.gnomview(input_maps[istk, :] - array_est_fg[0][0, istk, :], rot = center, reso = 15, sub = (1, 2, 1),
            title = '(1) - (2)', min = -nsig * sig1, max = nsig * sig1)
hp.gnomview(cmb_same_resol[0, istk, :] - array_est_fg[0][0, istk, :], rot = center, reso = 15, sub = (1, 2, 2), 
            title = '(2) - (3)', min = -nsig * sig2, max = nsig * sig2)
```

# For dust


We do now the same for Dust maps.

```{python}
# Get spectra
leff_dust_est, cells_dust_est, w_dust_est = Namaster.get_spectra(array_est_fg[1][indf], purify_e=False, 
                            purify_b=True, beam_correction=np.max(fwhmdegs), pixwin_correction=True)
```

```{python}
# Get spectra
leff_dust, cells_dust, w_dust = Namaster.get_spectra(dust_same_resol[indf], purify_e=False, 
                            purify_b=True, beam_correction=np.max(fwhmdegs), pixwin_correction=True)
```

We can fit the dust power spectrum by a power law :

$$C_\ell \approx \beta \ell^{- \alpha}$$

```{python}
from scipy.optimize import curve_fit
```

```{python}
def power_law(x, a, b):
    return a*np.power(x, b)
```

```{python}
def Dl_2_Cl(Dl, l) :
    return Dl * 2 * np.pi / (l*(l+1))
```

```{python}
Cl_est = np.zeros(cells_dust_est.shape)
Cl = np.zeros(cells_dust.shape)

for i in range(4) :
    Cl_est[:, i] = Dl_2_Cl(cells_dust_est[:, i], leff_dust_est)
    Cl[:, i] = Dl_2_Cl(cells_dust[:, i], leff_dust)
```

```{python}
alpha = []
beta = []
for i in range(1, 3) :
    pars, cov = curve_fit(f=power_law, xdata=leff_dust, ydata=Cl[:, i], p0=[2, 2], bounds=(-5, 5))
    alpha.append(np.round(pars[1], 3))
    beta.append(np.round(pars[0], 3))
```

```{python}
clnames = ['EE', 'BB']
plt.rc('figure', figsize=(16, 8))

plt.figure()
for i in range(1, 3) :
    plt.subplot(1, 2, i)
    plt.semilogy(leff_dust[:lmax], beta[i-1] * leff_dust[:lmax]**alpha[i-1], '--k', label = '$\\beta \\ell^{-\\alpha}$')
    plt.semilogy(leff_dust[:lmax], Cl[:lmax, i],'or', label = 'dust', markersize = 6)
    plt.semilogy(leff_dust_est[:lmax], Cl_est[:lmax, i],'xb', label = 'dust est', markersize = 10)
    plt.xlabel('$\\ell$')
    plt.ylabel('$C_\\ell$')
    plt.title(clnames[i-1] + '\n $\\alpha$ = {} \n $\\beta$ = {}'.format(-alpha[i-1], beta[i-1]))
    plt.legend()
plt.tight_layout()
plt.show()
```

```{python}

```

```{python}

```

```{python}

```

```{python}

```
