---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.4.0
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

# Simulations for calibration (fringes on the FP)

#### Edited by Louise 16-04-2021
selfcal_lib.py allows to do several simulations concerning the calibration, especially the simlation of the signal on the focal plane. This notebook gives some examples of what you can do with.

To simulate the signal on the FP, there are 3 possibilities:
 - Analytical simulation (only fringes, with a simple sine) 
 - Qubic soft simulation
 - Maynooth simulations (plotted through Qubic soft)
 
Each possibility corresponds to a python class in Selfcal_lib.py.

```{python pycharm={'is_executing': False}}
from __future__ import division, print_function

# %matplotlib inline
# %matplotlib notebook

import numpy as np
import scipy
import matplotlib.pyplot as plt
import matplotlib.ticker as plticker
from matplotlib.colors import SymLogNorm

from qubicpack.utilities import Qubic_DataDir
import qubic
from qubic import selfcal_lib as scal

plt.rcParams['figure.figsize'] = (12, 6)

```

```{python}
#save_dir = '/home/lmousset/QUBIC/Qubic_work/SpectroImagerie/paper_plot/'
save_dir = '/home/lmousset/QUBIC/These_manuscrit/Figures/Plots/'
```

```{python}
# Get a dictionary
d = qubic.qubicdict.qubicDict()
d.read_from_file('global_source_oneDet.dict')

d['MultiBand'] = False
d['nf_sub'] = 1
d['config'] = 'FI'
d['beam_shape'] = 'gaussian'
```

## Instrument detector and horn config

```{python}
# QubicInstrument
q = qubic.QubicInstrument(d)

plt.figure(figsize=(8, 6))
q.detector.plot(fill=True)
plt.axis('square')
plt.xlabel('X_GRF')
plt.ylabel('Y_GRF')
plt.title('q.detector.plot()')

# q.optics.focal_length = 0.30 # Change the focal length
```

```{python}
# Make a TD instrument
d1 = qubic.qubicdict.qubicDict()
d1.read_from_file('global_source_oneDet.dict')

d1['config'] = 'TD'
q1 = qubic.QubicInstrument(d1)

# Open or close switches
scal.open_switches(q, np.arange(1, 401))
scal.open_switches(q1, np.arange(1, 65))

# Plot the horn array
fig = plt.figure(figsize=(6, 6))
q.horn.plot(facecolor_open='white', facecolor_closed='grey', alpha=0.4)
q1.horn.plot(facecolor_open='y', facecolor_closed='g', alpha=0.3)

# plt.xlabel('$X_{GRF}$ [m]', fontsize=20)
# plt.ylabel('$Y_{GRF}$ [m]', fontsize=20)
plt.xlabel('$h_x$ [m]', fontsize=30)
plt.ylabel('$h_y$ [m]', fontsize=30)
plt.axis('square')
plt.rc('font', size=10) 
fig.tight_layout()
# plt.savefig(save_dir + 'horn_array.pdf', dpi=100)
```

#### Horn numbering
The instrument numbering goes from 1 to 64 and 1 to 400 for the FI as shown in the first figure.

On the contrary, the qubicsoft horn index given by `q.horn.index` consider that the FI horn array is placed on a squared grid 22 x 22, numbered from 0 to 483. This is shown in the secon plot.

```{python}
# Plot the horn array
fig = plt.figure(figsize=(10, 10))
q.horn.plot(facecolor_open='grey', alpha=0.2)
q1.horn.plot(facecolor_open='g', alpha=0.2)

# FI numbering
a = 1
x = q.horn.center[:, 0]
y = q.horn.center[:, 1]
for i,j in zip(x, y):
    corr = 0.001 # add a little correction to put annotation in marker's centrum
    plt.annotate(str(a),  xy=(i - corr-0.003, j - corr), fontsize=10, color='b')
    a += 1

# TD numbering
a = 1
x = q1.horn.center[:, 0]
y = q1.horn.center[:, 1]
for i,j in zip(x, y):
    corr = 0.001 # add a little correction to put annotation in marker's centrum
    plt.annotate(str(a),  xy=(i - (corr+0.001), j - (corr+0.005)), fontsize=10, color='r')
    a += 1

plt.xlabel('$X_{GRF}$ [m]', fontsize=30)
plt.ylabel('$Y_{GRF}$ [m]', fontsize=30)
plt.axis('square')
plt.rc('font', size=10) 
fig.tight_layout()
plt.savefig(save_dir + 'horn_array_numbering.pdf', bbox_inches='tight')
```

```{python}
# Plot the horn array
fig = plt.figure(figsize=(10, 10))
q.horn.plot(facecolor_open='grey', alpha=0.2)
q1.horn.plot(facecolor_open='g', alpha=0.2)

# Horn QUBIC soft indices
a = 1
x = q.horn.center[:, 0]
y = q.horn.center[:, 1]
for i,j in zip(x, y):
    corr = 0.001 # add a little correction to put annotation in marker's centrum
    plt.annotate(str(q.horn.index[a-1]),  xy=(i - corr-0.003, j - corr), fontsize=10, color='k')
    a += 1

plt.xlabel('$X_{GRF}$ [m]', fontsize=30)
plt.ylabel('$Y_{GRF}$ [m]', fontsize=30)
plt.axis('square')
plt.rc('font', size=10) 
fig.tight_layout()
plt.savefig(save_dir + 'horn_array_index.pdf', bbox_inches='tight')
```

#### Conversion from TD horn numbering to FI horn numbering

```{python}
d = qubic.qubicdict.qubicDict()
d.read_from_file('global_source_oneDet.dict')
hornFI = scal.horn_index_TD2FI(5, d)
print(hornFI)
```

## Analytical function to simulate fringes
It is simply a 2D sine on the focal plane to make fringes according to the focal length, the frequency, the position of the source. 

A gaussian apodization is done to represent the primary beam. The Gaussian is centered in (0, 0) when the source is on-axis (theta_source=0, phi_source=0.). It moves according to the position of the source. 

```{python}
baseline = [49, 51]
Model_Ana = scal.Model_Fringes_Ana(q, baseline, 
                                   theta_source=np.deg2rad(0), 
                                   phi_source=np.deg2rad(0), 
                                   nu_source=150e9, fwhm=20., amp=1., frame='ONAFP')
print(Model_Ana.focal)

xONAFP, yONAFP, fringes = Model_Ana.get_fringes(times_gaussian=True)

scal.scatter_plot_FP(q, xONAFP, yONAFP, fringes, frame='ONAFP', s=40, title=f'Baseline {baseline}', 
                     cmap='bwr', unit='[A.U.]')

#plt.savefig(save_dir + f'fringes_simu_ana_BL{baseline[0]}-{baseline[1]}.pdf', bbox_inches='tight')
```

# Qubic soft simulation (no aberrations)

This is a simulation that doesn't take into account optical aberrations (only geometrical optics). If the point source is on the optical axis, then you get a symmetrical image.

In general Qubic Soft uses only the GRF frame. However, selfcal_lib allows to use the ONAFP frame which is the one uned on the instrument.


#### Get the image on the focal plane for a given horn configuration


```{python}
scal.open_switches(q, np.arange(1, 401, 1))
# scal.close_switches(q, np.arange(1, 64))

xONAFP, yONAFP, power = scal.get_response_power(q, 0., 0., 150e9, 1.)
# xONAFP, yONAFP, _ = scal.get_response_power(q, 0., 0., 150e9, 1.)

fig = plt.figure(figsize=(10, 10))
ax = fig.gca()
scal.scatter_plot_FP(q, xONAFP, yONAFP, power, frame='ONAFP', title='', s=190, unit=None, cbar=None,
                      vmin=0, vmax=1.5e-5, fig=fig, ax=ax, fontsize=30, Norm=SymLogNorm(1e-6))
fig.tight_layout()
#plt.savefig(save_dir + 'detector_array.pdf', dpi=100)
```

#### Create a Fringes object

```{python}
TDbaseline = [49, 51] 
FIhorn_1 = scal.horn_index_TD2FI(TDbaseline[0], d)
FIhorn_2 = scal.horn_index_TD2FI(TDbaseline[1], d)
FIbaseline = [FIhorn_1, FIhorn_2]

Model_QS = scal.Model_Fringes_QubicSoft(q, FIbaseline,
                                        theta_source=0., phi_source=0.,
                                        nu_source=150e9, spec_irrad_source=1.,
                                        frame='ONAFP', external_A=None, hwp_position=0)
```

```{python}
# Information are store in the object
print(Model_QS.frame)
print(Model_QS.nu_source)
print(Model_QS.baseline)
```

#### Get fringes 

You can choose ONAFP or GRF frame.
Each pointing is defined by a position of the source (theta, phi).

```{python}
xONAFP, yONAFP, fringes = Model_QS.get_fringes(doplot=True, verbose=True, norm=None, s=30)

print('fringes shape:', fringes.shape)
```

```{python}
# Information are store in the object
print(Model_QS.x)
print(Model_QS.fringes)
```

#### Plot the fringes

There are 2 functions, one with scatter plot and the other with pcolor.
It is convenient to be sure of the coordinates and the image orientation. 

```{python}
fig, axs = plt.subplots(1, 2)
ax1, ax2 = np.ravel(axs)
fig.suptitle(f'Baseline: {baseline}', fontsize=18)
fig.subplots_adjust(wspace=0.3)

scal.scatter_plot_FP(q, xONAFP, yONAFP, fringes, frame='ONAFP', fig=fig, ax=ax1, 
                     title='Scatter plot', norm=None, s=30, cbar=True, fontsize=14)


scal.pcolor_plot_FP(q, xONAFP, yONAFP, fringes, frame='ONAFP', fig=fig, ax=ax2, 
                    title='pcolor plot', norm=None)
```

```{python}
scal.scatter_plot_FP(q, xONAFP, yONAFP, fringes*1e7, frame='ONAFP', fig=None, ax=None, 
                     title=f'Baseline: {TDbaseline}', norm=None, s=30, cbar=True, fontsize=14)

#plt.savefig(save_dir + f'fringes_simu_QS_BL{TDbaseline[0]}-{TDbaseline[1]}.pdf', bbox_inches='tight')
```

#### Get fringes from the combination 
This is what is actually done when we measure the fringes.

```{python}
# Get all combinations
x, y, S, Cminus_i, Sminus_ij, Cminus_j, Ci, Cj, Sij = Model_QS.get_all_combinations_power(doplot=True, 
                                                                                          verbose=True, 
                                                                                          norm=SymLogNorm(5e-8), 
                                                                                          s=40)

print('shape of each combination :', Cminus_i.shape)
```

```{python}
# Save plots for each configuration
scal.close_switches(q, np.arange(1, 401))
scal.open_switches(q, [252, 254])

fig, axs = plt.subplots(1, 2, figsize=(12, 6))
ax0, ax1 = np.ravel(axs)
fig.suptitle(r'$S_{ij}$ - Horn 254 open', fontsize=18)
fig.subplots_adjust(wspace=0.3)

scal.plot_horns(q, ax=ax0, s=180) # TD horn array
scal.scatter_plot_FP(q, xONAFP, yONAFP, Sij*1e7, frame='ONAFP', fig=fig, ax=ax1, 
                     title='', norm=None, s=40, cbar=True, fontsize=14)
fig.tight_layout()

#fig.savefig(save_dir + 'Sij.pdf', bbox_inches='tight')
```

#### Look at the cycle acquired during measurement

```{python}
cycle = np.array((S, Cminus_i, Sminus_ij, S, Cminus_j, S, S)) - S
cycle.shape
```

```{python}
# TEs ans ASIC numbers
tes = scal.get_all_tes_numbers(q)
```

```{python}
for i in [100, 120]:
    plt.figure(figsize=(10, 6))
    plt.step(np.arange(1, 8), cycle[:, i], where='post', color='r')
    
    plt.axvspan(1, 2, color='k', alpha=0.1, label=r'All open: $S_{\rm tot}$')
    plt.axvspan(4, 5, color='k', alpha=0.1)
    plt.axvspan(6, 7, color='k', alpha=0.1)
    plt.axvspan(2, 3, color='b', alpha=0.1, label=r'$h_1$ close: $C_{-i}$')
    plt.axvspan(3, 4, color='g', alpha=0.1, label=r'$h_1$ and $h_2$ close: $S_{-ij}$')
    plt.axvspan(5, 6, color='c', alpha=0.1, label=r'$h_2$ close: $C_{-j}$')
    
    plt.xlim(1, 7)
    plt.xticks(np.arange(1.5, 7.5), labels=('1', '2', '3', '4', '5', '6'))
    plt.xlabel('Step index', fontsize=16)
    plt.ylabel(r'Signal - $S_{\rm tot}$', fontsize=16)
    plt.title(f'TES {tes[i, 1]} - ASIC {tes[i, 0]}', fontsize=16)
    if i==100:
        plt.legend(loc='upper left', fontsize=16)
    
    plt.savefig(save_dir + f'fringes_cycle_simu_TES{tes[i, 1]}_ASIC{tes[i, 0]}_BL{baseline}.pdf', 
                bbox_inches='tight')
```

####  Make the combination to get the fringes

```{python}
# Complete one: S_tot - Cminus_i - Cminus_j + Sminus_ij + Ci +Cj
x, y, fringes_true = Model_QS.get_fringes_from_combination(measured_comb=False,
                                                           doplot=True, verbose=False, s=40)

# Measured one: S_tot - Cminus_i - Cminus_j + Sminus_ij
x, y, fringes_meas = Model_QS.get_fringes_from_combination(measured_comb=True,
                                                           doplot=True, verbose=False, s=40)
```

```{python}
# Look at the difference between both combinations

fig, axs = plt.subplots(1, 2)
ax1, ax2 = axs.ravel()
fig.suptitle(f'TD baseline: {TDbaseline}', fontsize=18)
fig.subplots_adjust(wspace=0.3)

scal.scatter_plot_FP(q, x, y, fringes_true*1e7, frame='ONAFP', 
                     fig=fig, ax=ax1, title='Complete combination', norm=None, s=40)

scal.scatter_plot_FP(q, x, y, fringes_meas*1e7, frame='ONAFP', 
                     fig=fig, ax=ax2, title='Measured combination', norm=None, s=40, cmap='bwr')
fig.tight_layout()
#fig.savefig(save_dir + f'fringes_compare_combinations_BL{TDbaseline[0]}-{TDbaseline[1]}.pdf', bbox_inches='tight')
```

# Power on the focal plane with Maynooth simulations

Those simulations include optical aberrations.
You need to download the files at : https://drive.google.com/open?id=19dPHw_CeuFZ068b-VRT7N-LWzOL1fmfG

They are only available for the **TD instrument**.

```{python}
# Path to the simulated files 
rep = Qubic_DataDir(datafile='detcentres.txt', datadir='/home/lmousset/QUBIC/')
print('rep:', rep)
```

#### Get the power on the FP for an arbitrary horn configuration

This simulations are done in the ONAFP frame. The resolution is high (241 x 241) and it assumes an area bigger than the focal plane.

```{python}
open_horns = [49, 51]#np.arange(1, 64)
xONAFP, yONAFP, power = scal.get_power_Maynooth(rep, open_horns, 
                                                0., 150e9, 
                                                q.horn.center,  
                                                hwp_position=0,
                                                verbose=True)
print(xONAFP.shape)
print(power.shape)

scal.scatter_plot_FP(q, xONAFP, yONAFP, power, s=1, 
                   frame='ONAFP', 
                   title='Maynooth full resolution', 
                   norm=None)
```

### Compare symmetric baselines (Figure 19 in paper QUBIC-III)

```{python}
open_horns1 = [60, 64]
xONAFP, yONAFP, power1 = scal.get_power_Maynooth(rep, open_horns1, 
                                                0., 150e9, 
                                                q.horn.center,  
                                                hwp_position=0,
                                                verbose=True)
open_horns2 = [1, 5]
xONAFP, yONAFP, power2 = scal.get_power_Maynooth(rep, open_horns2, 
                                                0., 150e9, 
                                                q.horn.center,  
                                                hwp_position=0,
                                                verbose=True)
print(xONAFP.shape)
print(power.shape)
fig, axs = plt.subplots(1, 3, figsize=(12, 6))
ax1, ax2, ax3 = np.ravel(axs)

scal.scatter_plot_FP(q, xONAFP, yONAFP, power1, s=1, 
                     fig=fig, ax=ax1,
                     frame='ONAFP', 
                     title=f'Baseline {open_horns1}',
                     unit='',
                     norm=None)
scal.scatter_plot_FP(q, xONAFP, yONAFP, power2, s=1, 
                     fig=fig, ax=ax2,
                     frame='ONAFP', 
                     title=f'Baseline {open_horns2}', 
                     unit='',
                     norm=None)
scal.scatter_plot_FP(q, xONAFP, yONAFP, power1 - power2, s=1, 
                     fig=fig, ax=ax3,
                     frame='ONAFP', 
                     title='Difference', 
                     unit='',
                     norm=None)
fig.tight_layout()
#fig.savefig('/home/lmousset/QUBIC/Papiers/QUBIC_III/symmetric_baselines60-64_1-5.pdf', bbox_inches='tight')
```

```{python}
# Make a plot for paper 3 without any axis
fig = plt.figure(figsize=(8, 8))
ax = fig.gca()
ax.axis('off')
scal.scatter_plot_FP(q, xONAFP, yONAFP, power, s=100, 
                   frame='ONAFP', 
                   title='', 
                   norm=None,
                   fig=fig, ax=ax,
                   cbar=False)
# fig.savefig('/home/lmousset/QUBIC/Images/plots/fringes_Maynoothsimu_BaselineTD57-64.png', transparent=True)
```

The following is an other way to do the same.

Qubic soft has an option `external_A` in `get_response()`. So I tried to use this option by passing Maynooth results in `external_A` but it is not fully working for now. There is a small bug.

```{python}
scal.open_switches(q, open_horns)

external_A = scal.make_external_A(rep, open_horns)

xONAFP, yONAFP, power = scal.get_response_power(q,
                                              theta=0., phi=0.,
                                              nu=150e9, spectral_irradiance=1.,
                                              frame='ONAFP',
                                              external_A=external_A, hwp_position=0, 
                                              verbose=True)

scal.scatter_plot_FP(q, xONAFP, yONAFP, power, s=100, 
                       frame='ONAFP', 
                       title='Maynooth full resolution', 
                       norm=None)
```

#### Get the fringes at TES resolution
To decrease the resolution, you can either make a real interpolation (`interp=True`) and then integrate or you can just make the mean inside each TES (`interp=False`). The second way is much faster.

```{python}
d['config'] = 'TD'
q = qubic.QubicInstrument(d)
baseline = [49, 51]  # for the TD

Model_Maynooth = scal.Model_Fringes_Maynooth(q, baseline, rep, 
                                             theta_source=0., nu_source=150e9,
                                             frame='ONAFP', interp=False, FIfocal_plane=True)
```

```{python}
# Information are store in the object
print(Model_Maynooth.frame)
print(Model_Maynooth.nu_source)
print(Model_Maynooth.baseline)
```

```{python}
# If you want to plot the FI focal plane
d['config'] = 'FI'
qFI = qubic.QubicInstrument(d)

xONAFP_new, yONAFP_new, fringes = Model_Maynooth.get_fringes(qFI=qFI, verbose=True)

fig, axs = plt.subplots(1, 2, figsize=(12, 6))
ax1, ax2 = axs.ravel()
scal.scatter_plot_FP(q, xONAFP, yONAFP, power, s=1, 
                     fig=fig, ax=ax1,
                     frame='ONAFP', 
                     title='Maynooth full resolution', 
                     config='FI',
                     norm=None)
ax1.set_xlim(-0.06, 0.06)
ax1.set_ylim(-0.06, 0.06)

scal.scatter_plot_FP(q, xONAFP_new, yONAFP_new, fringes, s=30, 
                     fig=fig, ax=ax2,
                     frame='ONAFP', 
                     title='Maynooth at TES resolution',
                     config='FI',
                     norm=None)
fig.tight_layout()
fig.savefig(save_dir + f'fringes_Maynooth_BL{TDbaseline[0]}-{TDbaseline[1]}.pdf', bbox_inches='tight')
```

#### Get the fringes at TES reso doing the combination

You can make the "true" combination or the measured one.

```{python}
xONAFP, yONAFP, fringes_comb = Model_Maynooth.get_fringes_from_combination(measured_comb=True, verbose=True)

scal.scatter_plot_FP(q, xONAFP, yONAFP, fringes_comb, s=200, 
                   frame='ONAFP', 
                   title='Maynooth TES resolution', 
                   norm=None)
```

```{python}

```
