---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.1
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

# Simulations for calibration (fringes on the FP)

#### Edited by Louise
selfcal_lib.py allows to do several simulations concerning the calibration, especially the simlation of the signal on the focal plane. This notebook gives some examples of what you can do with.

```{python pycharm={'is_executing': False}}
from __future__ import division, print_function

# %matplotlib inline
# %matplotlib notebook

import numpy as np
import healpy as hp
import matplotlib.pyplot as plt
import matplotlib.ticker as plticker

from qubicpack.utilities import Qubic_DataDir

import qubic

from qubic import selfcal_lib as sc

plt.rcParams['figure.figsize'] = (9, 9)


import matplotlib.animation as animation
from IPython.display import HTML
```

```{python}
# Use a tool from qubicpack to get a path
basedir = Qubic_DataDir(datafile='instrument.py', ) 
print('basedir : ', basedir)
dictfilename = basedir + '/dicts/global_source_oneDet.dict'

# Get a dictionary
d = qubic.qubicdict.qubicDict()
d.read_from_file(dictfilename)
print(d['detarray'])

# Create an object
baseline = [1, 8]
ca = sc.SelfCalibration(baseline, [], d)
```

# Qubic soft simulation (no aberrations)


### Get all combinations for one baseline
This is a simulation that doesn't take into account optical aberrations (only geometrical optics). If the point source is on the optical axis, then you get a symmetrical image.

```{python}
# You need a qubic instrument for that function
q = qubic.QubicInstrument(d)

# Focal length (if you want to change it)
# q.optics.focal_length = 0.30

# FP radius
radius = 0.051
S, Cminus_i, Cminus_j, Sminus_ij, Ci, Cj, Sij = ca.get_power_combinations(q, theta=[0], 
                                                                          phi=[0], nu=150e9, reso=34,
                                                                          xmin=-radius, xmax=radius)

# They are 3D arrays : (reso, reso, #pointings)
print('shape of each combination :', Cminus_i.shape)
```

### Fringes by combining the different horn configurations

```{python}
# Make the combination (S_tot - Cminus_i - Cminus_j + Sminus_ij) / Ci
fringes = ca.compute_fringes(q, theta=list(np.deg2rad(np.arange(0, 4, 0.25))), 
                                phi=list(np.zeros(16)), reso=34, nu=150e9,
                             xmin=-radius, xmax=radius)
print(fringes.shape)
```

```{python}
# Make an animation for different source positions
nfringes = fringes.shape[2]  
all_fringes = []
fig = plt.figure()
for i in range(nfringes):
    im = plt.imshow(fringes[:, :, i], animated=True)
    all_fringes.append([im])

ani = animation.ArtistAnimation(fig, all_fringes, interval=1000, repeat=False)

HTML(ani.to_html5_video())
# ani.save('fringes_passing.mp4')
```

### Get the focal plane image for the real instrument
#### Without taking into account space between quadrant

```{python}
# The focal plane image must already have 34x34 pixels
real_fringes = sc.get_real_fp(Sij[:, :, 0])

# Full focal plane
plt.subplot(321)
plt.imshow(real_fringes, origin='lower')

# Get only one quadrant:
real_fringes, real_fringes_quad = sc.get_real_fp(Sij[:,:,0], quadrant=3)
plt.subplot(322)
plt.imshow(real_fringes_quad, origin='lower')

# Remove dead detectors
# Build masks
full_mask, quart_mask = ca.get_dead_detectors_mask()
plt.subplot(323)
plt.imshow(full_mask, origin='lower')
plt.subplot(324)
plt.imshow(quart_mask, origin='lower')

# Apply the mask on the focal plane
plt.subplot(325)
plt.imshow(real_fringes*full_mask, origin='lower')
plt.subplot(326)
plt.imshow(real_fringes_quad*quart_mask, origin='lower')


```

```{python}
# Add a grid (quadrant and TES)
fig, ax = plt.subplots()
extent = [-radius, radius, -radius, radius]
ax.imshow(real_fringes, origin='lower', extent=extent)

det_size = 0.003
grid_ticks = np.arange(-radius, radius, det_size)
quadrant_ticks = np.arange(-radius, radius, radius)

ax.set_xticks(grid_ticks , minor=True)
ax.set_yticks(grid_ticks , minor=True)

ax.set_xticks(quadrant_ticks , minor=False)
ax.set_yticks(quadrant_ticks , minor=False)

ax.grid(which='major', color='w', linewidth=3)

ax.grid(which='minor', color='w', linewidth=0.5)
```

#### Using real TES locations

```{python}
# Average signal on the real FP (using real TES locations)

# Path to the simulated files 
rep = Qubic_DataDir(datafile='detcentres.txt')
print(rep)

readv, det_value = sc.averaging_tes_signal(Sij[:, :, 0], rep, 2*radius)
```

```{python}
# Plot
fig = sc.make_plot_real_fp(readv, det_value)
plt.title('Baseline {} No aberrations'.format(baseline))
```

```{python}
from matplotlib.patches import Circle
import matplotlib.ticker as plticker
import matplotlib.colors as colors
import matplotlib.cm as cmx
import matplotlib.patches as patches

def make_plot_real_fp(readv, det_value):
    """
    Plot real FP using TES locations.
    """
    # All this to get colormap
    cm = plt.get_cmap('viridis')
    # plot scale from average
    cNorm = colors.Normalize(vmin=0., vmax=1.5e-5)
    scalarMap = cmx.ScalarMappable(norm=cNorm, cmap=cm)
    scalarMap.set_array(det_value)

    fig, ax7 = plt.subplots()
    fig.figsize = (12, 12)
    for i in range(0, 992):
        rect = patches.Rectangle((readv[i, 2, 0], readv[i, 2, 1]),
                                 (readv[i, 0, 0] - readv[i, 1, 0]),
                                 (readv[i, 0, 1] - readv[i, 3, 1]),
                                 linewidth=1, edgecolor='none', facecolor=scalarMap.to_rgba(det_value[i, 2]))
        ax7.add_patch(rect)

    plt.xlim(-.055, .055)  # the focal plane
    plt.ylim(-.055, .055)
    ax7.set_aspect('equal')
    plt.colorbar(scalarMap)

    return fig

fig = make_plot_real_fp(readv, det_value)
```

# Power on the focal plane with optical aberrations
Using Creidhe simulations,
need to download the files at : https://drive.google.com/open?id=19dPHw_CeuFZ068b-VRT7N-LWzOL1fmfG

```{python}
# Path to the simulated files 
rep = Qubic_DataDir(datafile='detcentres.txt')
print('rep:', rep)

# Finges with aberations
# Directly using the 2 horns opened
fringes_aber = ca.get_power_fp_aberration(rep, theta_source=0., doplot=True)

print(fringes_aber.shape)

```

```{python}
# Other way to get fringes with aberrations :
# Make the combination (S_tot - Cminus_i - Cminus_j + Sminus_ij) / Ci
fringes_aber_comb = ca.get_fringes_aberration_combination(rep)
print('fringes_aber_comb.shape shape :', fringes_aber_comb.shape)

```

```{python}
# This simulation is larger than the FP 
# Let's overplot the real FP
# This is not exactly right because the 4 quadrants should be more separated... 
fringes_aber[fringes_aber==0]=['nan']

fig = sc.add_fp_simu_aber(fringes_aber, vmin=0., vmax=0.05)
# plt.savefig('/home/louisemousset/QUBIC/Qubic_images/plots/fringes_aber_25_57.png')
```

```{python}
# Get real FP by averaging the signal and using real TES locations.
readv_aber, det_value_aber = sc.averaging_tes_signal(fringes_aber, rep, 0.12)
```

```{python}
fig = sc.make_plot_real_fp(readv_aber, det_value_aber)
plt.title('Baseline {} with aberrations'.format(baseline))
```

### Test the "rotation problem"

Clearly, if there is a bug, it comes from the function get_power_fp_aberration fom selfcal_lib that I copied here with some simplifications in order to check it. 

```{python}
import glob
import pandas as pd
def get_power_fp_aberration(rep, doplot=True, theta_source=0., freq_source=150.):
    q = qubic.QubicInstrument(d)

    # Get simulation files
    files = sorted(glob.glob(rep + '/*.dat'))
#     for f in files:
#         print(f[98:104])

    # Get the sample number from the first file
    data0 = pd.read_csv(files[0], sep='\t', skiprows=0)
    nn = data0['X_Index'].iloc[-1] + 1
    print('Sampling number = {}'.format(nn))

    # Get all amplitudes and phases for each open horn
    open_horns = baseline
    nopen_horns = len(baseline)

    q.horn.open = False
    q.horn.open[np.asarray(open_horns) - 1] = True
    
#     q.horn.open = True
#     open_horns = np.arange(1, 65)
#     nopen_horns = 64
    
    horn_transpose = np.arange(64)
    horn_transpose = np.reshape(horn_transpose, (8, 8))
    horn_transpose = np.ravel(horn_transpose.T)
    print(horn_transpose)
    
    allampX = np.empty((nopen_horns, nn, nn))
    allphiX = np.empty((nopen_horns, nn, nn))
    allampY = np.empty((nopen_horns, nn, nn))
    allphiY = np.empty((nopen_horns, nn, nn))
    for i, swi in enumerate(open_horns):
        print('Horn ', swi, ': ', files[horn_transpose[swi-1]][98:104])
        data = pd.read_csv(files[horn_transpose[swi-1]], sep='\t', skiprows=0)

        allampX[i, :, :] = np.reshape(np.asarray(data['MagX']), (nn, nn)).T
        allampY[i, :, :] = np.reshape(np.asarray(data['MagY']), (nn, nn)).T

        allphiX[i, :, :] = np.reshape(np.asarray(data['PhaseX']), (nn, nn)).T
        allphiY[i, :, :] = np.reshape(np.asarray(data['PhaseY']), (nn, nn)).T

    # Electric field for each open horn
    Ax = allampX * (np.cos(allphiX) + 1j * np.sin(allphiX))
    Ay = allampY * (np.cos(allphiY) + 1j * np.sin(allphiY))

    # Sum of the electric fields
    sumampx = np.sum(Ax, axis=0)
    sumampy = np.sum(Ay, axis=0)

    # Power on the focal plane
    power = np.abs(sumampx) ** 2 + np.abs(sumampy) ** 2

    if doplot:
        plt.figure()
        plt.subplot(121)
        q.horn.plot()
        plt.axis('off')

        plt.subplot(122)
        plt.imshow(power, origin='lower')
        plt.title('Power at the sampling resolution')
        plt.colorbar()

    return power

# Using it, we immediatly see that the fringes don't have the right orientation...
baseline = [1, 57]
power = get_power_fp_aberration(rep)
```

```{python}
# In this cell, I check the way I am reading the .dat files and how I project the data on a 2D image. 
# I do the same as in the previous function but with the columns X and Y
# I don't see the problem, data look well projected...

nn = 241
files = sorted(glob.glob(rep + '/*.dat'))
print(files[0])
datfile = pd.read_csv(files[0], sep='\t', skiprows=0)

datfile['MagX'][5036:5045] = 10
print(datfile[5030:5050])

plt.figure()
MagX = np.reshape(np.asarray(datfile['MagX']), (nn, nn)).T
plt.imshow(MagX, origin='lower')
plt.colorbar()
plt.title('MagX')

plt.figure()
X = np.reshape(np.asarray(datfile['X']), (nn, nn)).T
plt.imshow(X, origin='lower')
plt.colorbar()
plt.title('X')
print('X=',X)

plt.figure()
Y = np.reshape(np.asarray(datfile['Y']), (nn, nn)).T
plt.imshow(Y, origin='lower')
plt.colorbar()
plt.title('Y')
print('Y=',Y)
```

# Instrument horn config

```{python}
q.horn.open=False # All close
q.horn.open[3]=True # Close one
q.horn
```

```{python}
# Power on the focal plane
power = sc.get_power_on_array(q, reso=200)
print('power shape :', power.shape)
plt.imshow(power[:,:,0])
```

```{python}
# Horn array in the GRF frame
center = q.horn.center
center.shape
x = center[:, 0]
y = center[:, 1]

fig, ax = plt.subplots()

# instanciate a figure and ax object
# annotate is a method that belongs to axes
ax.plot(x, y, 'go', markersize=23, alpha=0.5)

a = 1
for i,j in zip(x,y):
    corr = -0.001 # adds a little correction to put annotation in marker's centrum
    ax.annotate(str(a),  xy=(i + corr, j + corr))
    a+=1
```

# Get an array with TES signal

```{python}
signal = sc.image_fp2tes_signal(real_fringes)
print('shape : (#TES, #ASICS)', signal.shape)
```

```{python}
# Do the inverse
image_fp = sc.tes_signal2image_fp(signal, asics=np.arange(1, 9))
plt.imshow(image_fp, origin='lower')
```

# Synthetic Beam on the sky

```{python}
# For the function, you need a instrument and a scene
q = qubic.QubicInstrument(d)
d['nside'] = 512
s = qubic.QubicScene(d)

q.horn.open = False
open_horns = [1, 5]
for i in open_horns:
    q.horn.open[i] = True
    
external_A = sc.make_external_A(rep, open_horns=np.where(q.horn.open==True)[0])

sb = q.get_synthbeam(s, idet=93, external_A=external_A, hwp_position=0)

# The synthetic beam optained has a value for each pixel on the sky. 
# You should use Healpy if you want to plot it.
print('sb shape :', sb.shape)
```

```{python}
idet = 93
sb0 = q.get_synthbeam(s, idet=idet, external_A=external_A, hwp_position=0)
hp.gnomview(sb0, sub=(131), rot=[0, 90], reso=10, title='TES={}, HWP 0'.format(idet), min=0, max=5e4)

sb1 = q.get_synthbeam(s, idet=idet, external_A=external_A, hwp_position=7)
hp.gnomview(sb1, sub=(132), rot=[0, 90], reso=10, title='TES={}, HWP 7'.format(idet), min=0, max=5e4)

hp.gnomview(np.abs(sb1-sb0), sub=(133), rot=[0, 90], reso=10, title='|Difference|', min=0, max=5e4)
```

# Michel simulation
Analytical function to fit the fringes measurement.
Because of aberations, the fitted focal length was 35cm instead of 30cm.

```{python}
# The function that Michel used
def sim_fringe(param):
   Amp = param[0]
   f = param[1]
   phase = param[2]
   yc = 0. #param[3]
   xc = 0. #param[4]
   alpha = param[3]
   #w = param[4]
   allres = np.ones(256)
   mask = ft.image_asics(all1=allres)
   mask[0,12:]=np.nan
   mask[1:5,16]=np.nan
   mask[np.isnan(mask)]=0
   nu=150e9
   lam=3e8/nu
   bl=14e-3*4.#baseline
   #f=300e-3 # focal length
   fringe=np.zeros_like(mask)
   i, j = np.mgrid[0:17, 0:17]
   freq=bl/lam
   #w=np.sqrt(2*(12.9*np.pi/180*f/2.355)**2)
   w=40.87e-3 # From Creidhe
   #alpha = 90.
   fringe=Amp*np.cos(2.*np.pi*freq*(i*np.cos(alpha*np.pi/180)+j*np.sin(alpha*np.pi/180))*3e-3/f+phase)*mask*np.exp(-((16-i+xc)**2+(j-yc)**2)*3e-3**2/(w**2))
   return fringe.astype(np.float64)
```

```{python}
# Same function as Michel rewritten to understand how it works
def sim_fringe_new(Amp, phase, det_dist=3e-3, focal=0.3,
                   baseline=14.e-3*4., nu=150.e9, alpha=-45.,
                   w=40.87e-3, yc=0., xc=0.):

    lam = 3.e8/nu
    alpha_rad = np.deg2rad(alpha)
    
    ndet = 17
    fringe = np.zeros((ndet, ndet))
    i, j = np.mgrid[0:ndet, 0:ndet]
    
    #w=np.sqrt(2*(12.9*np.pi/180*f/2.355)**2)
    
    gaussian = np.exp(-((16-i+xc)**2 + (j-yc)**2) * det_dist**2 / (w**2))
    xprime = (i * np.cos(alpha_rad) + j * np.sin(alpha_rad)) * det_dist
    interfrange = lam * focal / baseline
    fringe = Amp * np.cos((2. * np.pi / interfrange * xprime) + phase)# * gaussian
    
    return fringe

# Using the parameters that Michel found with the fit
fringes = sim_fringe_new(1., 0.277, focal=0.35, alpha=-44.4)
s = 0.051
extent = (-s, 0, -s, 0)
plt.figure()
plt.imshow(fringes, origin='lower', extent=extent)
```

```{python}

```

```{python}

```
